'use strict';

const CONFIG = Object.freeze({
  WIDTH:960,HEIGHT:540,MAX_DELTA:0.033,MAX_ENEMY_LEVEL:4,TIME_LIMIT:90,TARGET_SCORE:18000,DEFENSE:12,
  CLEANUP_MARGIN:100,DEFENSE_LINE_X:66,ENEMY_CAP_START:7,ENEMY_CAP_END:16,DIFFICULTY_RAMP:75,
  COLORS:{space:'#030619',navy:'#07102b',cyan:'#42f5ff',blue:'#608cff',pink:'#ff4fcc',red:'#ff466d',white:'#f4ffff',grid:'#1d4978',green:'#87ff8a',yellow:'#ffe66b'},
  PLAYER:{START_X:145,START_Y:270,RADIUS:19,HITBOX:6,HP:3,SPEED:355,SLOW_FACTOR:.38,POINTER_LERP:15,INVINCIBILITY:1.65,BULLET_CLEAR_RADIUS:145,FLASH_INTERVAL:.1,BODY_DAMAGE:1},
  PUSH:{INTERVAL:.22,BUFF_INTERVAL:.13,SPEED:650,DAMAGE:1,RADIUS:5,HORIZONTAL_FORCE:150,BUFF_HORIZONTAL_FORCE:245,VERTICAL_FORCE:-210,DAMPING:.94,PENETRATION_HITS:4},
  BREAK:{DAMAGE:22,DURATION:.22,COOLDOWN:5.5,HALF_HEIGHT:18,START_OFFSET:15,END_MARGIN:12},
  ENEMY_LEVELS:{
    1:{RADIUS:18,HP:7,SCORE:100,SPEED:30,COLOR:'#55eaff',FIRE_INTERVAL:3.1,ESCAPE_DAMAGE:1,SHOT_COUNT:1,SPREAD:0,BULLET_SPEED:145},
    2:{RADIUS:27,HP:18,SCORE:350,SPEED:36,COLOR:'#86ff79',FIRE_INTERVAL:2.5,ESCAPE_DAMAGE:2,SHOT_COUNT:2,SPREAD:.18,BULLET_SPEED:165},
    3:{RADIUS:38,HP:42,SCORE:1200,SPEED:42,COLOR:'#ffe568',FIRE_INTERVAL:1.9,ESCAPE_DAMAGE:4,SHOT_COUNT:3,SPREAD:.24,BULLET_SPEED:185},
    4:{RADIUS:51,HP:90,SCORE:4000,SPEED:48,COLOR:'#ff685f',FIRE_INTERVAL:1.35,ESCAPE_DAMAGE:8,SHOT_COUNT:7,SPREAD:.22,BULLET_SPEED:205}
  },
  ENEMY_BULLET_RADIUS:6,ENEMY_PUSH_DAMPING:.94,ENEMY_BOUNCE:.65,ENEMY_SPEED_RAMP:.3,FIRE_INTERVAL_RAMP:.22,
  SPAWN:{START_INTERVAL:1.65,END_INTERVAL:.72,MIN_Y_PADDING:6,PAIR_BIAS:.64,PAIR_Y_VARIANCE:32},
  MERGE:{DELAY:0,PROTECTION:.42,SEPARATION:.52,EPSILON:.0001,RING_LIFE:.65},
  COMBO:{TIMEOUT:3.4,STEP:.12,MAX_MULTIPLIER:3},
  BUFF:{FIRE_RATE_DURATION:7,PUSH_POWER_DURATION:7,PENETRATION_DURATION:8},
  PARTICLE:{MAX:420,DESTROY_COUNT:18,MERGE_COUNT:30,HIT_COUNT:16,SPEED:185,LIFE:.72,SIZE:3,DRAG:.97},
  TEXT:{LIFE:1.05,RISE_SPEED:36},SHAKE:{HIT:10,MERGE:7,DESTROY:4,DECAY:28},
  BACKGROUND:{STAR_COUNT:88,STAR_SPEED:20,GRID_GAP:60,GRID_SPEED:34,GRID_HORIZON:190},
  RENDER:{GLOW:18,LINE:2,FULL_CIRCLE:Math.PI*2,ENEMY_SIDES:6,HP_BAR_WIDTH:1.5,WARNING_PULSE:5},
  INPUT:{NONE:-1},IDS:{START:1},TIME:{MINUTE:60,PAD:2},RANDOM:{HALF:.5}
});

const gameState={
  phase:'start',result:null,elapsedTime:0,score:0,targetScore:CONFIG.TARGET_SCORE,combo:0,comboTimer:0,scoreMultiplier:1,
  player:null,enemies:[],pushBullets:[],enemyBullets:[],particles:[],floatingTexts:[],mergeQueue:[],mergingEnemyIds:new Set(),
  breakShot:{active:false,timer:0,cooldown:0,hitEnemyIds:new Set()},buffs:{fireRate:0,pushPower:0,penetration:0},defense:CONFIG.DEFENSE,
  spawnTimers:{enemy:0},input:{pointerX:CONFIG.PLAYER.START_X,pointerY:CONFIG.PLAYER.START_Y,pointerSeen:false,pointerDown:false,pointerId:CONFIG.INPUT.NONE,slowMode:false,breakRequested:false,keys:new Set()},
  screenShake:0,lastTimestamp:0,entityId:CONFIG.IDS.START,backgroundOffset:0,stars:[],dom:{},ctx:null,animationFrame:null
};

const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const random=(min,max)=>min+Math.random()*(max-min);
const squaredDistance=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y;};
const nextId=()=>gameState.entityId++;

function cacheDom(){
  ['game-canvas','score','target-score','multiplier','combo','hp','defense','remaining-time','break-cooldown','break-fill','buffs','start-overlay','result-overlay','result-kicker','result-title','final-score','start-button','restart-button'].forEach(id=>gameState.dom[id]=document.getElementById(id));
  const canvas=gameState.dom['game-canvas'];gameState.ctx=canvas?canvas.getContext('2d'):null;
}
function createPlayer(){return {id:nextId(),type:'player',active:true,x:CONFIG.PLAYER.START_X,y:CONFIG.PLAYER.START_Y,radius:CONFIG.PLAYER.RADIUS,hitRadius:CONFIG.PLAYER.HITBOX,hp:CONFIG.PLAYER.HP,maxHp:CONFIG.PLAYER.HP,invincible:0,fireTimer:0};}
function createStars(){gameState.stars=Array.from({length:CONFIG.BACKGROUND.STAR_COUNT},()=>({x:Math.random()*CONFIG.WIDTH,y:Math.random()*CONFIG.HEIGHT,size:random(1,3),depth:random(.35,1)}));}
function resetGame(){
  gameState.result=null;gameState.elapsedTime=0;gameState.score=0;gameState.targetScore=CONFIG.TARGET_SCORE;gameState.combo=0;gameState.comboTimer=0;gameState.scoreMultiplier=1;
  gameState.entityId=CONFIG.IDS.START;gameState.player=createPlayer();gameState.enemies=[];gameState.pushBullets=[];gameState.enemyBullets=[];gameState.particles=[];gameState.floatingTexts=[];gameState.mergeQueue=[];gameState.mergingEnemyIds=new Set();
  gameState.breakShot={active:false,timer:0,cooldown:0,hitEnemyIds:new Set()};gameState.buffs={fireRate:0,pushPower:0,penetration:0};gameState.defense=CONFIG.DEFENSE;gameState.spawnTimers={enemy:.35};
  gameState.input.pointerX=CONFIG.PLAYER.START_X;gameState.input.pointerY=CONFIG.PLAYER.START_Y;gameState.input.pointerSeen=false;gameState.input.pointerDown=false;gameState.input.pointerId=CONFIG.INPUT.NONE;gameState.input.slowMode=false;gameState.input.breakRequested=false;gameState.input.keys=new Set();
  gameState.screenShake=0;gameState.lastTimestamp=0;gameState.backgroundOffset=0;createStars();syncHud();
}
function setPhase(phase){gameState.phase=phase;gameState.dom['start-overlay']?.classList.toggle('hidden',phase!=='start');gameState.dom['result-overlay']?.classList.toggle('hidden',phase!=='gameover');}
function startGame(){resetGame();setPhase('playing');}
function restartGame(){startGame();}
function pointerPosition(event){const canvas=gameState.dom['game-canvas'],rect=canvas?.getBoundingClientRect();if(!canvas||!rect||rect.width<=0||rect.height<=0)return;gameState.input.pointerX=clamp((event.clientX-rect.left)*CONFIG.WIDTH/rect.width,CONFIG.PLAYER.RADIUS,CONFIG.WIDTH-CONFIG.PLAYER.RADIUS);gameState.input.pointerY=clamp((event.clientY-rect.top)*CONFIG.HEIGHT/rect.height,CONFIG.PLAYER.RADIUS,CONFIG.HEIGHT-CONFIG.PLAYER.RADIUS);gameState.input.pointerSeen=true;}
function requestBreakShot(){if(gameState.phase==='playing')gameState.input.breakRequested=true;}
function bindEvents(){
  const canvas=gameState.dom['game-canvas'],stop=e=>e.stopPropagation();
  gameState.dom['start-button']?.addEventListener('pointerdown',stop);gameState.dom['restart-button']?.addEventListener('pointerdown',stop);gameState.dom['start-button']?.addEventListener('click',startGame);gameState.dom['restart-button']?.addEventListener('click',restartGame);
  canvas?.addEventListener('pointermove',e=>{if(gameState.phase==='playing')pointerPosition(e);});
  canvas?.addEventListener('pointerdown',e=>{if(gameState.phase!=='playing'||e.button!==0)return;pointerPosition(e);gameState.input.pointerDown=true;gameState.input.slowMode=true;gameState.input.pointerId=e.pointerId;canvas.setPointerCapture(e.pointerId);requestBreakShot();e.preventDefault();});
  const release=e=>{if(e.pointerId!==gameState.input.pointerId)return;gameState.input.pointerDown=false;gameState.input.pointerId=CONFIG.INPUT.NONE;gameState.input.slowMode=gameState.input.keys.has('ShiftLeft')||gameState.input.keys.has('ShiftRight');};canvas?.addEventListener('pointerup',release);canvas?.addEventListener('pointercancel',release);
  window.addEventListener('keydown',e=>{if(gameState.phase!=='playing')return;const movement=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'];if(movement.includes(e.code)){gameState.input.keys.add(e.code);gameState.input.slowMode=e.shiftKey||gameState.input.pointerDown;e.preventDefault();}if(e.code==='Space'){if(!e.repeat)requestBreakShot();e.preventDefault();}});
  window.addEventListener('keyup',e=>{gameState.input.keys.delete(e.code);gameState.input.slowMode=gameState.input.pointerDown||gameState.input.keys.has('ShiftLeft')||gameState.input.keys.has('ShiftRight');});window.addEventListener('blur',()=>{gameState.input.keys.clear();gameState.input.slowMode=gameState.input.pointerDown;});
}
function createEnemy(level,x=CONFIG.WIDTH+CONFIG.ENEMY_LEVELS[level].RADIUS,y=random(CONFIG.ENEMY_LEVELS[level].RADIUS,CONFIG.HEIGHT-CONFIG.ENEMY_LEVELS[level].RADIUS),vx=0,vy=0){
  const def=CONFIG.ENEMY_LEVELS[level];if(!def)return null;return {id:nextId(),type:'enemy',active:true,level,x,y,vx,vy,radius:def.RADIUS,hp:def.HP,maxHp:def.HP,score:def.SCORE,fireTimer:random(def.FIRE_INTERVAL*.5,def.FIRE_INTERVAL),mergeProtectionTimer:0,age:0};
}
function createPushBullet(){const p=gameState.player;if(!p)return null;return {id:nextId(),type:'pushBullet',active:true,x:p.x+p.radius,y:p.y,vx:CONFIG.PUSH.SPEED,vy:0,radius:CONFIG.PUSH.RADIUS,damage:CONFIG.PUSH.DAMAGE,hitsLeft:gameState.buffs.penetration>0?CONFIG.PUSH.PENETRATION_HITS:1,hitIds:new Set()};}
function createEnemyBullet(enemy,angle){const def=CONFIG.ENEMY_LEVELS[enemy.level];return {id:nextId(),type:'enemyBullet',active:true,x:enemy.x-enemy.radius*.55,y:enemy.y,vx:Math.cos(angle)*def.BULLET_SPEED,vy:Math.sin(angle)*def.BULLET_SPEED,radius:CONFIG.ENEMY_BULLET_RADIUS};}
function activateBreakShot(){if(gameState.breakShot.active||gameState.breakShot.cooldown>0)return;gameState.breakShot.active=true;gameState.breakShot.timer=CONFIG.BREAK.DURATION;gameState.breakShot.cooldown=CONFIG.BREAK.COOLDOWN;gameState.breakShot.hitEnemyIds.clear();gameState.screenShake=Math.max(gameState.screenShake,CONFIG.SHAKE.MERGE);}
function update(dt){
  if(gameState.phase!=='playing')return;gameState.elapsedTime+=dt;gameState.backgroundOffset+=CONFIG.BACKGROUND.STAR_SPEED*dt;
  updatePlayer(dt);updatePlayerFiring(dt);updateBreakShot(dt);updateBuffs(dt);updateCombo(dt);updateSpawning(dt);updateEnemies(dt);updateEnemyFiring(dt);updateBullets(dt);updateEffects(dt);
  checkPushBulletCollisions();checkBreakShotCollisions();checkPlayerCollisions();checkEnemyPairCollisions();processMergeQueue();cleanupEntities();
  if(gameState.phase==='playing'&&gameState.score>=gameState.targetScore)triggerClear();else if(gameState.phase==='playing'&&gameState.elapsedTime>=CONFIG.TIME_LIMIT)triggerDefeat();syncHud();
}
function updatePlayer(dt){const p=gameState.player;if(!p?.active)return;p.invincible=Math.max(0,p.invincible-dt);let dx=0,dy=0,k=gameState.input.keys;if(k.has('ArrowLeft')||k.has('KeyA'))dx--;if(k.has('ArrowRight')||k.has('KeyD'))dx++;if(k.has('ArrowUp')||k.has('KeyW'))dy--;if(k.has('ArrowDown')||k.has('KeyS'))dy++;const slow=gameState.input.slowMode?CONFIG.PLAYER.SLOW_FACTOR:1;if(dx||dy){const length=Math.hypot(dx,dy)||1;p.x+=dx/length*CONFIG.PLAYER.SPEED*slow*dt;p.y+=dy/length*CONFIG.PLAYER.SPEED*slow*dt;}else if(gameState.input.pointerSeen){const amount=clamp(CONFIG.PLAYER.POINTER_LERP*slow*dt,0,1);p.x+=(gameState.input.pointerX-p.x)*amount;p.y+=(gameState.input.pointerY-p.y)*amount;}p.x=clamp(p.x,p.radius,CONFIG.WIDTH-p.radius);p.y=clamp(p.y,p.radius,CONFIG.HEIGHT-p.radius);}
function updatePlayerFiring(dt){const p=gameState.player;if(!p)return;p.fireTimer-=dt;if(p.fireTimer<=0){const bullet=createPushBullet();if(bullet)gameState.pushBullets.push(bullet);p.fireTimer=gameState.buffs.fireRate>0?CONFIG.PUSH.BUFF_INTERVAL:CONFIG.PUSH.INTERVAL;}}
function updateBreakShot(dt){if(gameState.input.breakRequested){activateBreakShot();gameState.input.breakRequested=false;}gameState.breakShot.cooldown=Math.max(0,gameState.breakShot.cooldown-dt);if(gameState.breakShot.active){gameState.breakShot.timer=Math.max(0,gameState.breakShot.timer-dt);if(gameState.breakShot.timer<=0)gameState.breakShot.active=false;}}
function updateBuffs(dt){Object.keys(gameState.buffs).forEach(key=>gameState.buffs[key]=Math.max(0,gameState.buffs[key]-dt));}
function updateCombo(dt){if(gameState.combo<=0)return;gameState.comboTimer=Math.max(0,gameState.comboTimer-dt);if(gameState.comboTimer<=0)resetCombo();}
function updateSpawning(dt){gameState.spawnTimers.enemy-=dt;const progress=clamp(gameState.elapsedTime/CONFIG.DIFFICULTY_RAMP,0,1),cap=Math.floor(CONFIG.ENEMY_CAP_START+(CONFIG.ENEMY_CAP_END-CONFIG.ENEMY_CAP_START)*progress);if(gameState.spawnTimers.enemy>0||gameState.enemies.length>=cap)return;let y=random(CONFIG.ENEMY_LEVELS[1].RADIUS+CONFIG.SPAWN.MIN_Y_PADDING,CONFIG.HEIGHT-CONFIG.ENEMY_LEVELS[1].RADIUS-CONFIG.SPAWN.MIN_Y_PADDING);const recent=gameState.enemies.filter(e=>e?.active&&e.level===1&&e.x>CONFIG.WIDTH*.58);if(recent.length&&Math.random()<CONFIG.SPAWN.PAIR_BIAS)y=clamp(recent[recent.length-1].y+random(-CONFIG.SPAWN.PAIR_Y_VARIANCE,CONFIG.SPAWN.PAIR_Y_VARIANCE),CONFIG.ENEMY_LEVELS[1].RADIUS,CONFIG.HEIGHT-CONFIG.ENEMY_LEVELS[1].RADIUS);const enemy=createEnemy(1,undefined,y);if(enemy)gameState.enemies.push(enemy);gameState.spawnTimers.enemy=CONFIG.SPAWN.START_INTERVAL+(CONFIG.SPAWN.END_INTERVAL-CONFIG.SPAWN.START_INTERVAL)*progress;}
function updateEnemies(dt){const progress=clamp(gameState.elapsedTime/CONFIG.DIFFICULTY_RAMP,0,1);gameState.enemies.forEach(e=>{if(!e?.active)return;const def=CONFIG.ENEMY_LEVELS[e.level];e.age+=dt;e.mergeProtectionTimer=Math.max(0,e.mergeProtectionTimer-dt);e.x+=(-def.SPEED*(1+progress*CONFIG.ENEMY_SPEED_RAMP)+e.vx)*dt;e.y+=e.vy*dt;e.vx*=Math.pow(CONFIG.ENEMY_PUSH_DAMPING,dt*60);e.vy*=Math.pow(CONFIG.ENEMY_PUSH_DAMPING,dt*60);if(e.y-e.radius<0){e.y=e.radius;e.vy=Math.abs(e.vy)*CONFIG.ENEMY_BOUNCE;}else if(e.y+e.radius>CONFIG.HEIGHT){e.y=CONFIG.HEIGHT-e.radius;e.vy=-Math.abs(e.vy)*CONFIG.ENEMY_BOUNCE;}if(e.x+e.radius<CONFIG.DEFENSE_LINE_X)handleEnemyEscape(e);});}
function updateEnemyFiring(dt){const p=gameState.player,progress=clamp(gameState.elapsedTime/CONFIG.DIFFICULTY_RAMP,0,1);if(!p)return;gameState.enemies.forEach(e=>{if(!e?.active)return;e.fireTimer-=dt;if(e.fireTimer>0)return;const def=CONFIG.ENEMY_LEVELS[e.level],aim=Math.atan2(p.y-e.y,p.x-e.x),center=(def.SHOT_COUNT-1)*.5;for(let i=0;i<def.SHOT_COUNT;i++)gameState.enemyBullets.push(createEnemyBullet(e,aim+(i-center)*def.SPREAD));e.fireTimer=def.FIRE_INTERVAL*(1-progress*CONFIG.FIRE_INTERVAL_RAMP);});}
function updateBullets(dt){[gameState.pushBullets,gameState.enemyBullets].forEach(list=>list.forEach(b=>{if(!b?.active)return;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<-CONFIG.CLEANUP_MARGIN||b.x>CONFIG.WIDTH+CONFIG.CLEANUP_MARGIN||b.y<-CONFIG.CLEANUP_MARGIN||b.y>CONFIG.HEIGHT+CONFIG.CLEANUP_MARGIN)b.active=false;}));}
function updateEffects(dt){gameState.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=CONFIG.PARTICLE.DRAG;p.vy*=CONFIG.PARTICLE.DRAG;p.life-=dt;p.radius+=p.ring?CONFIG.MERGE.RING_LIFE*60*dt:0;});gameState.floatingTexts.forEach(t=>{t.y-=CONFIG.TEXT.RISE_SPEED*dt;t.life-=dt;});gameState.screenShake=Math.max(0,gameState.screenShake-CONFIG.SHAKE.DECAY*dt);}
function checkPushBulletCollisions(){gameState.pushBullets.forEach(b=>{if(!b?.active)return;gameState.enemies.forEach(e=>{if(!e?.active||!b.active||b.hitIds.has(e.id))return;const range=b.radius+e.radius;if(squaredDistance(b,e)>range*range)return;b.hitIds.add(e.id);const offsetY=clamp((b.y-e.y)/Math.max(e.radius,CONFIG.MERGE.EPSILON),-1,1),force=gameState.buffs.pushPower>0?CONFIG.PUSH.BUFF_HORIZONTAL_FORCE:CONFIG.PUSH.HORIZONTAL_FORCE;e.vx+=force;e.vy+=CONFIG.PUSH.VERTICAL_FORCE*offsetY;damageEnemy(e,b.damage);b.hitsLeft--;if(b.hitsLeft<=0)b.active=false;spawnParticles(b.x,b.y,CONFIG.COLORS.cyan,4);});});}
function checkBreakShotCollisions(){const p=gameState.player,s=gameState.breakShot;if(!p||!s.active)return;gameState.enemies.forEach(e=>{if(!e?.active||s.hitEnemyIds.has(e.id)||e.x+e.radius<p.x+CONFIG.BREAK.START_OFFSET)return;if(Math.abs(e.y-p.y)<=CONFIG.BREAK.HALF_HEIGHT+e.radius){s.hitEnemyIds.add(e.id);damageEnemy(e,CONFIG.BREAK.DAMAGE);spawnParticles(e.x,e.y,CONFIG.COLORS.white,CONFIG.PARTICLE.HIT_COUNT);}});}
function checkPlayerCollisions(){const p=gameState.player;if(!p?.active)return;gameState.enemyBullets.forEach(b=>{if(!b?.active)return;const r=b.radius+p.hitRadius;if(squaredDistance(b,p)<=r*r){b.active=false;damagePlayer();}});gameState.enemies.forEach(e=>{if(!e?.active)return;const r=e.radius+p.hitRadius;if(squaredDistance(e,p)<=r*r)damagePlayer();});}
function checkEnemyPairCollisions(){for(let i=0;i<gameState.enemies.length;i++){const a=gameState.enemies[i];if(!a?.active||gameState.mergingEnemyIds.has(a.id))continue;for(let j=i+1;j<gameState.enemies.length;j++){const b=gameState.enemies[j];if(!b?.active||gameState.mergingEnemyIds.has(b.id))continue;const r=a.radius+b.radius,dx=b.x-a.x,dy=b.y-a.y,distSq=dx*dx+dy*dy;if(distSq>r*r)continue;separateEnemies(a,b,dx,dy,distSq,r);if(a.level===b.level&&a.level<CONFIG.MAX_ENEMY_LEVEL&&a.mergeProtectionTimer<=0&&b.mergeProtectionTimer<=0)enqueueEnemyMerge(a,b);}}}
function separateEnemies(a,b,dx,dy,distSq,minDistance){let nx,ny,distance;if(distSq<CONFIG.MERGE.EPSILON){nx=(a.id+b.id)%2===0?1:-1;ny=0;distance=0;}else{distance=Math.sqrt(distSq);nx=dx/distance;ny=dy/distance;}const move=(minDistance-distance)*CONFIG.MERGE.SEPARATION;a.x-=nx*move*.5;a.y-=ny*move*.5;b.x+=nx*move*.5;b.y+=ny*move*.5;}
function enqueueEnemyMerge(a,b){if(!a?.active||!b?.active||gameState.mergingEnemyIds.has(a.id)||gameState.mergingEnemyIds.has(b.id))return;gameState.mergingEnemyIds.add(a.id);gameState.mergingEnemyIds.add(b.id);gameState.mergeQueue.push({aId:a.id,bId:b.id});}
function processMergeQueue(){const queue=gameState.mergeQueue.splice(0);queue.forEach(item=>mergeEnemies(item));}
function mergeEnemies(item){const a=gameState.enemies.find(e=>e?.id===item.aId),b=gameState.enemies.find(e=>e?.id===item.bId);gameState.mergingEnemyIds.delete(item.aId);gameState.mergingEnemyIds.delete(item.bId);if(!a?.active||!b?.active||a.level!==b.level||a.level>=CONFIG.MAX_ENEMY_LEVEL)return;const x=(a.x+b.x)*.5,y=(a.y+b.y)*.5,vx=(a.vx+b.vx)*.5,vy=(a.vy+b.vy)*.5;a.active=false;b.active=false;const merged=createEnemy(a.level+1,x,y,vx,vy);if(!merged)return;merged.mergeProtectionTimer=CONFIG.MERGE.PROTECTION;gameState.enemies.push(merged);increaseCombo();spawnParticles(x,y,CONFIG.ENEMY_LEVELS[merged.level].COLOR,CONFIG.PARTICLE.MERGE_COUNT);spawnRing(x,y,CONFIG.ENEMY_LEVELS[merged.level].COLOR);addFloatingText(x,y,`MERGE → LV.${merged.level}`,CONFIG.ENEMY_LEVELS[merged.level].COLOR);gameState.screenShake=Math.max(gameState.screenShake,CONFIG.SHAKE.MERGE);}
function damageEnemy(enemy,damage){if(!enemy?.active)return;enemy.hp-=damage;if(enemy.hp<=0)destroyEnemy(enemy);}
function destroyEnemy(enemy){if(!enemy?.active)return;enemy.active=false;const multiplier=getMultiplier(),points=Math.round(enemy.score*multiplier);gameState.score+=points;increaseCombo();spawnParticles(enemy.x,enemy.y,CONFIG.ENEMY_LEVELS[enemy.level].COLOR,CONFIG.PARTICLE.DESTROY_COUNT);addFloatingText(enemy.x,enemy.y,`+${points}`,CONFIG.COLORS.white);gameState.screenShake=Math.max(gameState.screenShake,CONFIG.SHAKE.DESTROY);if(enemy.level===2)gameState.buffs.fireRate=CONFIG.BUFF.FIRE_RATE_DURATION;if(enemy.level===3)gameState.buffs.pushPower=CONFIG.BUFF.PUSH_POWER_DURATION;if(enemy.level===4)gameState.buffs.penetration=CONFIG.BUFF.PENETRATION_DURATION;}
function increaseCombo(){gameState.combo++;gameState.comboTimer=CONFIG.COMBO.TIMEOUT;gameState.scoreMultiplier=getMultiplier();}
function getMultiplier(){return clamp(1+gameState.combo*CONFIG.COMBO.STEP,1,CONFIG.COMBO.MAX_MULTIPLIER);}
function resetCombo(){gameState.combo=0;gameState.comboTimer=0;gameState.scoreMultiplier=1;}
function damagePlayer(){const p=gameState.player;if(!p||p.invincible>0||gameState.phase!=='playing')return;p.hp-=CONFIG.PLAYER.BODY_DAMAGE;p.invincible=CONFIG.PLAYER.INVINCIBILITY;resetCombo();gameState.enemyBullets.forEach(b=>{if(b?.active&&squaredDistance(b,p)<=CONFIG.PLAYER.BULLET_CLEAR_RADIUS**2)b.active=false;});spawnParticles(p.x,p.y,CONFIG.COLORS.red,CONFIG.PARTICLE.HIT_COUNT);addFloatingText(p.x,p.y,'HULL HIT',CONFIG.COLORS.red);gameState.screenShake=CONFIG.SHAKE.HIT;if(p.hp<=0)triggerDefeat();}
function handleEnemyEscape(enemy){if(!enemy?.active)return;enemy.active=false;gameState.defense=Math.max(0,gameState.defense-CONFIG.ENEMY_LEVELS[enemy.level].ESCAPE_DAMAGE);resetCombo();addFloatingText(CONFIG.DEFENSE_LINE_X+25,enemy.y,`BREACH -${CONFIG.ENEMY_LEVELS[enemy.level].ESCAPE_DAMAGE}`,CONFIG.COLORS.red);spawnParticles(CONFIG.DEFENSE_LINE_X,enemy.y,CONFIG.COLORS.red,CONFIG.PARTICLE.HIT_COUNT);gameState.screenShake=CONFIG.SHAKE.HIT;if(gameState.defense<=0)triggerDefeat();}
function spawnParticles(x,y,color,count){const available=Math.max(0,CONFIG.PARTICLE.MAX-gameState.particles.length);for(let i=0;i<Math.min(count,available);i++){const angle=Math.random()*CONFIG.RENDER.FULL_CIRCLE,speed=random(CONFIG.PARTICLE.SPEED*.25,CONFIG.PARTICLE.SPEED);gameState.particles.push({id:nextId(),active:true,x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,color,size:random(1,CONFIG.PARTICLE.SIZE),life:CONFIG.PARTICLE.LIFE,maxLife:CONFIG.PARTICLE.LIFE,ring:false,radius:0});}}
function spawnRing(x,y,color){gameState.particles.push({id:nextId(),active:true,x,y,vx:0,vy:0,color,size:CONFIG.RENDER.LINE,life:CONFIG.MERGE.RING_LIFE,maxLife:CONFIG.MERGE.RING_LIFE,ring:true,radius:8});}
function addFloatingText(x,y,text,color){gameState.floatingTexts.push({id:nextId(),active:true,x,y,text,color,life:CONFIG.TEXT.LIFE,maxLife:CONFIG.TEXT.LIFE});}
function cleanupEntities(){gameState.enemies=gameState.enemies.filter(e=>e?.active);gameState.pushBullets=gameState.pushBullets.filter(e=>e?.active);gameState.enemyBullets=gameState.enemyBullets.filter(e=>e?.active);gameState.particles=gameState.particles.filter(e=>e?.active&&e.life>0);gameState.floatingTexts=gameState.floatingTexts.filter(e=>e?.active&&e.life>0);const activeIds=new Set(gameState.enemies.map(e=>e.id));for(const id of gameState.mergingEnemyIds)if(!activeIds.has(id))gameState.mergingEnemyIds.delete(id);}
function triggerClear(){if(gameState.phase!=='playing')return;gameState.result='clear';setPhase('gameover');syncResult();}
function triggerDefeat(){if(gameState.phase!=='playing')return;gameState.result='defeat';setPhase('gameover');syncResult();}
function syncResult(){const clear=gameState.result==='clear';gameState.dom['result-kicker'].textContent=clear?'TARGET SCORE ACQUIRED':'MISSION ENDED';gameState.dom['result-title'].textContent=clear?'SECTOR SECURED':'DEFENSE FAILED';gameState.dom['final-score'].textContent=gameState.score.toLocaleString();}
function syncHud(){const set=(id,value)=>{if(gameState.dom[id])gameState.dom[id].textContent=value;};set('score',String(gameState.score).padStart(6,'0'));set('target-score',String(gameState.targetScore));set('multiplier',`×${getMultiplier().toFixed(1)}`);set('combo',String(gameState.combo));set('hp',gameState.player?'◆ '.repeat(gameState.player.hp).trim():'');set('defense',String(gameState.defense));const remaining=Math.max(0,CONFIG.TIME_LIMIT-gameState.elapsedTime);set('remaining-time',`${String(Math.floor(remaining/CONFIG.TIME.MINUTE)).padStart(CONFIG.TIME.PAD,'0')}:${String(Math.ceil(remaining%CONFIG.TIME.MINUTE)).padStart(CONFIG.TIME.PAD,'0')}`);set('break-cooldown',gameState.breakShot.cooldown<=0?'READY':`${gameState.breakShot.cooldown.toFixed(1)}s`);if(gameState.dom['break-fill'])gameState.dom['break-fill'].style.width=`${(1-gameState.breakShot.cooldown/CONFIG.BREAK.COOLDOWN)*100}%`;const buffs=[];if(gameState.buffs.fireRate>0)buffs.push(`RAPID ${gameState.buffs.fireRate.toFixed(1)}s`);if(gameState.buffs.pushPower>0)buffs.push(`POWER ${gameState.buffs.pushPower.toFixed(1)}s`);if(gameState.buffs.penetration>0)buffs.push(`PIERCE ${gameState.buffs.penetration.toFixed(1)}s`);set('buffs',buffs.join('  //  ')||'STANDARD PUSH');}

function render(){const ctx=gameState.ctx;if(!ctx)return;ctx.save();ctx.clearRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);if(gameState.screenShake>0)ctx.translate(random(-gameState.screenShake,gameState.screenShake),random(-gameState.screenShake,gameState.screenShake));renderBackground(ctx);renderDefenseLine(ctx);renderPushBullets(ctx);renderEnemyBullets(ctx);renderEnemies(ctx);renderPlayer(ctx);renderBreakShot(ctx);renderParticles(ctx);renderFloatingTexts(ctx);renderHudEffects(ctx);ctx.restore();}
function renderBackground(ctx){ctx.fillStyle=CONFIG.COLORS.space;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);const glow=ctx.createRadialGradient(CONFIG.WIDTH*.7,CONFIG.HEIGHT*.35,0,CONFIG.WIDTH*.7,CONFIG.HEIGHT*.35,CONFIG.WIDTH*.65);glow.addColorStop(0,'#15285a');glow.addColorStop(1,'#03061900');ctx.fillStyle=glow;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);ctx.fillStyle=CONFIG.COLORS.white;gameState.stars.forEach(s=>{const x=(s.x-gameState.backgroundOffset*s.depth+CONFIG.WIDTH)%CONFIG.WIDTH;ctx.globalAlpha=.35+s.depth*.55;ctx.fillRect(x,s.y,s.size,s.size);});ctx.globalAlpha=1;ctx.strokeStyle=CONFIG.COLORS.grid;ctx.globalAlpha=.42;ctx.lineWidth=1;const horizon=CONFIG.BACKGROUND.GRID_HORIZON;for(let x=-CONFIG.WIDTH;x<CONFIG.WIDTH*2;x+=CONFIG.BACKGROUND.GRID_GAP){ctx.beginPath();ctx.moveTo(CONFIG.WIDTH*.5,horizon);ctx.lineTo(x,CONFIG.HEIGHT);ctx.stroke();}const offset=(gameState.backgroundOffset*CONFIG.BACKGROUND.GRID_SPEED/CONFIG.BACKGROUND.STAR_SPEED)%CONFIG.BACKGROUND.GRID_GAP;for(let y=horizon+CONFIG.BACKGROUND.GRID_GAP-offset;y<CONFIG.HEIGHT;y+=CONFIG.BACKGROUND.GRID_GAP){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CONFIG.WIDTH,y);ctx.stroke();}ctx.globalAlpha=1;}
function renderDefenseLine(ctx){ctx.save();ctx.strokeStyle=CONFIG.COLORS.cyan;ctx.shadowColor=CONFIG.COLORS.cyan;ctx.shadowBlur=CONFIG.RENDER.GLOW;ctx.setLineDash([9,8]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(CONFIG.DEFENSE_LINE_X,0);ctx.lineTo(CONFIG.DEFENSE_LINE_X,CONFIG.HEIGHT);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=CONFIG.COLORS.cyan;ctx.font='700 11px ui-monospace';ctx.translate(CONFIG.DEFENSE_LINE_X-9,CONFIG.HEIGHT*.5);ctx.rotate(-Math.PI*.5);ctx.fillText('DEFENSE LINE',0,0);ctx.restore();}
function renderPlayer(ctx){const p=gameState.player;if(!p)return;if(p.invincible>0&&Math.floor(p.invincible/CONFIG.PLAYER.FLASH_INTERVAL)%2===0)return;ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor=CONFIG.COLORS.cyan;ctx.shadowBlur=CONFIG.RENDER.GLOW;ctx.fillStyle=CONFIG.COLORS.cyan;ctx.beginPath();ctx.moveTo(p.radius,0);ctx.lineTo(-p.radius,-p.radius*.7);ctx.lineTo(-p.radius*.5,0);ctx.lineTo(-p.radius,p.radius*.7);ctx.closePath();ctx.fill();ctx.fillStyle=CONFIG.COLORS.white;ctx.fillRect(-3,-3,9,6);ctx.restore();if(gameState.input.slowMode)renderHitbox(ctx);}
function renderHitbox(ctx){const p=gameState.player;if(!p)return;ctx.save();ctx.strokeStyle=CONFIG.COLORS.white;ctx.shadowColor=CONFIG.COLORS.cyan;ctx.shadowBlur=10;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,p.hitRadius,0,CONFIG.RENDER.FULL_CIRCLE);ctx.stroke();ctx.restore();}
function renderPushBullets(ctx){ctx.save();ctx.strokeStyle=CONFIG.COLORS.cyan;ctx.shadowColor=CONFIG.COLORS.cyan;ctx.shadowBlur=12;ctx.lineWidth=4;gameState.pushBullets.forEach(b=>{ctx.beginPath();ctx.moveTo(b.x-15,b.y);ctx.lineTo(b.x+5,b.y);ctx.stroke();});ctx.restore();}
function renderEnemyBullets(ctx){ctx.save();ctx.fillStyle=CONFIG.COLORS.pink;ctx.shadowColor=CONFIG.COLORS.pink;ctx.shadowBlur=12;gameState.enemyBullets.forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.radius,0,CONFIG.RENDER.FULL_CIRCLE);ctx.fill();});ctx.restore();}
function renderEnemies(ctx){gameState.enemies.forEach(e=>{const def=CONFIG.ENEMY_LEVELS[e.level];ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.age*(e.level%2?1:-1));ctx.strokeStyle=def.COLOR;ctx.fillStyle=`${def.COLOR}22`;ctx.shadowColor=def.COLOR;ctx.shadowBlur=CONFIG.RENDER.GLOW+(e.level===4?Math.sin(e.age*CONFIG.RENDER.WARNING_PULSE)*8:0);ctx.lineWidth=2+e.level*.5;polygon(ctx,e.radius,CONFIG.RENDER.ENEMY_SIDES+e.level);ctx.fill();ctx.stroke();for(let ring=1;ring<e.level;ring++){ctx.rotate(.35);ctx.beginPath();ctx.arc(0,0,e.radius*(.35+ring*.14),0,CONFIG.RENDER.FULL_CIRCLE);ctx.stroke();}ctx.fillStyle=def.COLOR;ctx.beginPath();ctx.arc(0,0,3+e.level*2,0,CONFIG.RENDER.FULL_CIRCLE);ctx.fill();ctx.rotate(-e.age*(e.level%2?1:-1));ctx.fillStyle='#071020';ctx.fillRect(-e.radius,-e.radius-9,e.radius*2,4);ctx.fillStyle=def.COLOR;ctx.fillRect(-e.radius,-e.radius-9,e.radius*2*clamp(e.hp/e.maxHp,0,1),4);ctx.restore();});}
function polygon(ctx,radius,sides){ctx.beginPath();for(let i=0;i<sides;i++){const angle=i/sides*CONFIG.RENDER.FULL_CIRCLE-Math.PI*.5,px=Math.cos(angle)*radius,py=Math.sin(angle)*radius;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.closePath();}
function renderBreakShot(ctx){const p=gameState.player,s=gameState.breakShot;if(!p||!s.active)return;const alpha=clamp(s.timer/CONFIG.BREAK.DURATION,0,1),gradient=ctx.createLinearGradient(p.x,p.y,CONFIG.WIDTH,p.y);gradient.addColorStop(0,CONFIG.COLORS.white);gradient.addColorStop(.4,CONFIG.COLORS.cyan);gradient.addColorStop(1,'#42f5ff00');ctx.save();ctx.globalAlpha=.5+alpha*.5;ctx.strokeStyle=gradient;ctx.shadowColor=CONFIG.COLORS.cyan;ctx.shadowBlur=30;ctx.lineWidth=CONFIG.BREAK.HALF_HEIGHT*(.7+alpha);ctx.beginPath();ctx.moveTo(p.x+CONFIG.BREAK.START_OFFSET,p.y);ctx.lineTo(CONFIG.WIDTH-CONFIG.BREAK.END_MARGIN,p.y);ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle=CONFIG.COLORS.white;ctx.stroke();ctx.restore();}
function renderParticles(ctx){gameState.particles.forEach(p=>{ctx.save();ctx.globalAlpha=clamp(p.life/p.maxLife,0,1);ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=8;if(p.ring){ctx.lineWidth=p.size;ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,CONFIG.RENDER.FULL_CIRCLE);ctx.stroke();}else{ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.restore();});}
function renderFloatingTexts(ctx){ctx.save();ctx.textAlign='center';ctx.font='700 15px ui-monospace';gameState.floatingTexts.forEach(t=>{ctx.globalAlpha=clamp(t.life/t.maxLife,0,1);ctx.fillStyle=t.color;ctx.shadowColor=t.color;ctx.shadowBlur=8;ctx.fillText(t.text,t.x,t.y);});ctx.restore();}
function renderHudEffects(ctx){if(gameState.phase!=='playing')return;const progress=clamp(gameState.score/gameState.targetScore,0,1);ctx.fillStyle='#050918bb';ctx.fillRect(CONFIG.WIDTH*.25,12,CONFIG.WIDTH*.5,8);ctx.fillStyle=CONFIG.COLORS.cyan;ctx.fillRect(CONFIG.WIDTH*.25,12,CONFIG.WIDTH*.5*progress,8);ctx.strokeStyle=CONFIG.COLORS.white;ctx.strokeRect(CONFIG.WIDTH*.25,12,CONFIG.WIDTH*.5,8);}
function gameLoop(timestamp){const dt=gameState.lastTimestamp?Math.min((timestamp-gameState.lastTimestamp)/1000,CONFIG.MAX_DELTA):0;gameState.lastTimestamp=timestamp;if(gameState.phase==='playing')update(dt);render();gameState.animationFrame=requestAnimationFrame(gameLoop);}
function initialize(){cacheDom();resetGame();bindEvents();setPhase('start');gameState.animationFrame=requestAnimationFrame(gameLoop);}
document.addEventListener('DOMContentLoaded',initialize,{once:true});
