"use strict";

const CONFIG = Object.freeze({
  WIDTH:960, HEIGHT:540, TAU:Math.PI*2, MAX_DELTA:0.033, START_X:154, START_Y:330,
  COLORS:{sky:"#07131f",sky2:"#10283a",ground:"#101c23",line:"#35515c",cyan:"#63f5e5",orange:"#ff9e45",red:"#ff626b",white:"#edf8f5",enemy:"#d9e4df",shadow:"#02070b"},
  PLAYER:{RADIUS:22,HITBOX:13,HP:4,SPEED:350,CATCH_MOVE_MULTIPLIER:.4,THROW_MOVE_MULTIPLIER:.18,HURT_MOVE_MULTIPLIER:.35,INVINCIBILITY:1.05,HURT_DURATION:.34,MOVE_MIN_X:42,MOVE_MAX_X:430,MOVE_MIN_Y:128,MOVE_MAX_Y:468,POINTER_DEADZONE:7,POINTER_STOP:12},
  CATCH:{RADIUS:62,OFFSET:40,FORWARD_DOT:.08,JUST_WINDOW:.18,NORMAL_RECOVERY:.2,JUST_RECOVERY:.025,HIT_STOP:.045,JUST_HIT_STOP:.085,INVINCIBILITY:.22,RUSH_WINDOW:.58},
  THROW:{RECOVERY:.38,RUSH_RECOVERY:.1,SPAWN_OFFSET:35,RECOIL:.16},
  ENEMY:{RADIUS:27,HP:2,ENTER_SPEED:150,MAX_ACTIVE:3,SPAWN_INTERVAL:1.55,SPAWN_INITIAL:.3,SPAWN_X:1010,COMBAT_X_MIN:690,COMBAT_X_GAP:92,Y_MIN:178,Y_MAX:435,THROW_INTERVAL_MIN:1.7,THROW_INTERVAL_MAX:2.7,TELEGRAPH:.72,RECOVERY:.5,HIT_DELAY:.45,HIT_FLASH:.14,DEFEAT_TIME:.42,KNOCKBACK:48,SEPARATION:70},
  BALL:{RADIUS:11,SPEED:285,DAMAGE:1,RETURN_POWER:1,RETURN_SPEED:650,RUSH_SPEED:900,RETURN_DAMAGE:1,JUST_DAMAGE_MULTIPLIER:2,CLEANUP_MARGIN:90,PENETRATION:false},
  SCORE:{NORMAL_CATCH:50,JUST_CATCH:175,RETURN_HIT:125,RUSH_HIT:250,DEFEAT:500},
  COMBO:{TIMEOUT:3,NORMAL_CATCH:1,JUST_CATCH:2,RETURN_HIT:1,RUSH:2,DEFEAT:2},
  TARGET:{DISTANCE_WEIGHT:1,DIRECTION_WEIGHT:240,FRONT_BONUS:180,SCREEN_MARGIN:30},
  FX:{PARTICLE_COUNT:8,STRONG_PARTICLE_COUNT:18,PARTICLE_LIFE:.48,PARTICLE_SPEED:180,RING_LIFE:.3,TEXT_LIFE:.72,SHAKE_SMALL:3,SHAKE_BIG:10,FLASH_NORMAL:.12,FLASH_JUST:.25,TRAIL_LIFE:.18,HIT_STOP_SCALE:.16},
  ENCOUNTER:{TARGET_DEFEATS:10},
  VIEW:{GROUND_Y:475,GRID_GAP:80,LIGHT_COUNT:12,SCROLL_SPEED:13,HP_GLYPH:"●",SCORE_DIGITS:6}
});

const gameState={
  phase:"start",result:null,elapsedTime:0,score:0,combo:0,comboTimer:0,player:null,enemies:[],incomingBalls:[],returnedBalls:[],particles:[],floatingTexts:[],rings:[],trails:[],heldBall:null,targetEnemyId:null,
  input:{pointerX:CONFIG.START_X,pointerY:CONFIG.START_Y,pointerActive:false,catchHeld:false,keyboardCatch:false,pointerCatch:false,catchPressedAt:-Infinity,throwRequested:false,keys:new Set()},
  spawnTimers:{enemy:0},encounter:{defeatedEnemies:0,targetDefeats:CONFIG.ENCOUNTER.TARGET_DEFEATS},returnRush:null,screenShake:0,screenFlash:0,hitStop:0,lastTimestamp:0,nextEntityId:1,animationFrame:null,listenersBound:false,dom:{},ctx:null
};

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const randomRange=(min,max)=>min+Math.random()*(max-min);
const length=(x,y)=>Math.hypot(x,y);
const safeDirection=(x,y,fallbackX=1,fallbackY=0)=>{const magnitude=length(x,y);return magnitude>Number.EPSILON?{x:x/magnitude,y:y/magnitude}:{x:fallbackX,y:fallbackY};};
const overlaps=(a,b,radiusA=a.radius,radiusB=b.radius)=>((a.x-b.x)**2+(a.y-b.y)**2)<=(radiusA+radiusB)**2;
const nextId=()=>gameState.nextEntityId++;

function cacheDom(){["game-canvas","screen","score","combo","hp","held","progress","start-overlay","result-overlay","result-kicker","result-title","final-score","start-button","restart-button"].forEach(id=>gameState.dom[id]=document.getElementById(id));gameState.ctx=gameState.dom["game-canvas"].getContext("2d");}
function createPlayer(){return{x:CONFIG.START_X,y:CONFIG.START_Y,radius:CONFIG.PLAYER.RADIUS,hp:CONFIG.PLAYER.HP,maxHp:CONFIG.PLAYER.HP,facingX:1,facingY:0,actionState:"normal",actionTimer:0,invincibilityTimer:0,recoilTimer:0,hitFlashTimer:0};}
function resetGame(){gameState.result=null;gameState.elapsedTime=0;gameState.score=0;gameState.combo=0;gameState.comboTimer=0;gameState.player=createPlayer();gameState.enemies=[];gameState.incomingBalls=[];gameState.returnedBalls=[];gameState.particles=[];gameState.floatingTexts=[];gameState.rings=[];gameState.trails=[];gameState.heldBall=null;gameState.targetEnemyId=null;gameState.input.keys.clear();Object.assign(gameState.input,{pointerX:CONFIG.START_X,pointerY:CONFIG.START_Y,pointerActive:false,catchHeld:false,keyboardCatch:false,pointerCatch:false,catchPressedAt:-Infinity,throwRequested:false});gameState.spawnTimers.enemy=CONFIG.ENEMY.SPAWN_INITIAL;gameState.encounter={defeatedEnemies:0,targetDefeats:CONFIG.ENCOUNTER.TARGET_DEFEATS};gameState.returnRush=null;gameState.screenShake=0;gameState.screenFlash=0;gameState.hitStop=0;gameState.nextEntityId=1;syncHud();}
function setPhase(phase){gameState.phase=phase;gameState.dom["start-overlay"].classList.toggle("hidden",phase!=="start");gameState.dom["result-overlay"].classList.toggle("hidden",phase!=="gameover");}
function startGame(){resetGame();setPhase("playing");}
function restartGame(){startGame();}

function bindEvents(){if(gameState.listenersBound)return;gameState.listenersBound=true;const canvas=gameState.dom["game-canvas"];
  const updatePointer=event=>{const rect=canvas.getBoundingClientRect();gameState.input.pointerX=clamp((event.clientX-rect.left)*CONFIG.WIDTH/rect.width,CONFIG.PLAYER.MOVE_MIN_X,CONFIG.PLAYER.MOVE_MAX_X);gameState.input.pointerY=clamp((event.clientY-rect.top)*CONFIG.HEIGHT/rect.height,CONFIG.PLAYER.MOVE_MIN_Y,CONFIG.PLAYER.MOVE_MAX_Y);gameState.input.pointerActive=true;};
  const refreshCatch=()=>{const held=gameState.input.keyboardCatch||gameState.input.pointerCatch;if(held&&!gameState.input.catchHeld&&gameState.phase==="playing")gameState.input.catchPressedAt=gameState.elapsedTime;gameState.input.catchHeld=held;};
  window.addEventListener("keydown",event=>{if(["Space","ShiftLeft","ShiftRight","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(event.code))event.preventDefault();gameState.input.keys.add(event.code);if(event.code==="ShiftLeft"||event.code==="ShiftRight"){gameState.input.keyboardCatch=true;refreshCatch();}if(event.code==="Space"&&!event.repeat)requestThrow();});
  window.addEventListener("keyup",event=>{gameState.input.keys.delete(event.code);if(event.code==="ShiftLeft"||event.code==="ShiftRight"){gameState.input.keyboardCatch=false;refreshCatch();}});
  canvas.addEventListener("pointermove",updatePointer);canvas.addEventListener("pointerdown",event=>{event.preventDefault();updatePointer(event);canvas.setPointerCapture?.(event.pointerId);if(event.button===0){gameState.input.pointerCatch=true;refreshCatch();}else if(event.button===2)requestThrow();});
  const pointerUp=event=>{if(event.button===0){gameState.input.pointerCatch=false;refreshCatch();}};canvas.addEventListener("pointerup",pointerUp);canvas.addEventListener("pointercancel",pointerUp);canvas.addEventListener("contextmenu",event=>event.preventDefault());
  [gameState.dom["start-button"],gameState.dom["restart-button"]].forEach(button=>{["pointerdown","pointerup","click"].forEach(type=>button.addEventListener(type,event=>event.stopPropagation()));});gameState.dom["start-button"].addEventListener("click",startGame);gameState.dom["restart-button"].addEventListener("click",restartGame);
  window.addEventListener("blur",()=>{gameState.input.keys.clear();gameState.input.keyboardCatch=false;gameState.input.pointerCatch=false;refreshCatch();});
}

function update(deltaTime){if(gameState.phase!=="playing")return;if(gameState.hitStop>0){gameState.hitStop=Math.max(0,gameState.hitStop-deltaTime);deltaTime*=CONFIG.FX.HIT_STOP_SCALE;}gameState.elapsedTime+=deltaTime;updateInput();updatePlayerActionState(deltaTime);updatePlayer(deltaTime);updateEnemies(deltaTime);validateTarget();updateIncomingBalls(deltaTime);checkCatchCollisions();updateReturnedBalls(deltaTime);updateCombo(deltaTime);updateEffects(deltaTime);cleanupEntities();if(gameState.player.hp<=0)triggerDefeat();else if(gameState.encounter.defeatedEnemies>=gameState.encounter.targetDefeats)triggerClear();syncHud();}
function updateInput(){if(gameState.input.throwRequested){gameState.input.throwRequested=false;throwHeldBall();}}
function updatePlayerActionState(dt){const p=gameState.player;p.actionTimer=Math.max(0,p.actionTimer-dt);p.invincibilityTimer=Math.max(0,p.invincibilityTimer-dt);p.recoilTimer=Math.max(0,p.recoilTimer-dt);p.hitFlashTimer=Math.max(0,p.hitFlashTimer-dt);if(gameState.returnRush){gameState.returnRush.timer=Math.max(0,gameState.returnRush.timer-dt);if(gameState.returnRush.timer<=0)gameState.returnRush=null;}if(p.actionTimer<=0&&["catchRecovery","throwing","hurt"].includes(p.actionState))p.actionState="normal";if(["normal","catching"].includes(p.actionState))p.actionState=gameState.input.catchHeld?"catching":"normal";}
function updatePlayer(dt){const p=gameState.player;if(!p)return;let dx=0,dy=0;const keys=gameState.input.keys;if(keys.has("KeyA")||keys.has("ArrowLeft"))dx--;if(keys.has("KeyD")||keys.has("ArrowRight"))dx++;if(keys.has("KeyW")||keys.has("ArrowUp"))dy--;if(keys.has("KeyS")||keys.has("ArrowDown"))dy++;let multiplier=p.actionState==="catching"?CONFIG.PLAYER.CATCH_MOVE_MULTIPLIER:p.actionState==="throwing"?CONFIG.PLAYER.THROW_MOVE_MULTIPLIER:p.actionState==="hurt"?CONFIG.PLAYER.HURT_MOVE_MULTIPLIER:1;const keyboard=dx!==0||dy!==0;if(keyboard){const dir=safeDirection(dx,dy);p.x+=dir.x*CONFIG.PLAYER.SPEED*multiplier*dt;p.y+=dir.y*CONFIG.PLAYER.SPEED*multiplier*dt;gameState.input.pointerActive=false;}else if(gameState.input.pointerActive){const px=gameState.input.pointerX-p.x,py=gameState.input.pointerY-p.y,dist=length(px,py);if(dist>CONFIG.PLAYER.POINTER_DEADZONE){const dir=safeDirection(px,py);const step=Math.min(CONFIG.PLAYER.SPEED*multiplier*dt,Math.max(0,dist-CONFIG.PLAYER.POINTER_STOP));p.x+=dir.x*step;p.y+=dir.y*step;}}p.x=clamp(p.x,CONFIG.PLAYER.MOVE_MIN_X+p.radius,CONFIG.PLAYER.MOVE_MAX_X-p.radius);p.y=clamp(p.y,CONFIG.PLAYER.MOVE_MIN_Y+p.radius,CONFIG.PLAYER.MOVE_MAX_Y-p.radius);}

function createEnemy(){const activeCount=gameState.enemies.filter(e=>e.active&&e.state!=="defeated").length;if(activeCount>=CONFIG.ENEMY.MAX_ACTIVE)return null;const slot=activeCount;const enemy={id:nextId(),type:"basicThrower",active:true,x:CONFIG.ENEMY.SPAWN_X,y:clamp(randomRange(CONFIG.ENEMY.Y_MIN,CONFIG.ENEMY.Y_MAX),CONFIG.ENEMY.Y_MIN+slot*CONFIG.ENEMY.SEPARATION/CONFIG.ENEMY.MAX_ACTIVE,CONFIG.ENEMY.Y_MAX),radius:CONFIG.ENEMY.RADIUS,hp:CONFIG.ENEMY.HP,maxHp:CONFIG.ENEMY.HP,state:"entering",stateTimer:0,throwTimer:randomRange(CONFIG.ENEMY.THROW_INTERVAL_MIN,CONFIG.ENEMY.THROW_INTERVAL_MAX),hitFlashTimer:0,combatX:CONFIG.ENEMY.COMBAT_X_MIN+slot*CONFIG.ENEMY.COMBAT_X_GAP,knockback:0};gameState.enemies.push(enemy);return enemy;}
function updateEnemies(dt){gameState.spawnTimers.enemy=Math.max(0,gameState.spawnTimers.enemy-dt);if(gameState.spawnTimers.enemy<=0&&gameState.encounter.defeatedEnemies+gameState.enemies.filter(e=>e.active).length<gameState.encounter.targetDefeats){if(createEnemy())gameState.spawnTimers.enemy=CONFIG.ENEMY.SPAWN_INTERVAL;}for(const enemy of gameState.enemies)updateEnemyState(enemy,dt);}
function updateEnemyState(enemy,dt){if(!enemy.active)return;enemy.hitFlashTimer=Math.max(0,enemy.hitFlashTimer-dt);enemy.stateTimer=Math.max(0,enemy.stateTimer-dt);enemy.knockback=Math.max(0,enemy.knockback-CONFIG.ENEMY.KNOCKBACK*dt);if(enemy.state==="defeated"){enemy.x+=CONFIG.ENEMY.KNOCKBACK*dt;if(enemy.stateTimer<=0)enemy.active=false;return;}if(enemy.state==="entering"){enemy.x-=CONFIG.ENEMY.ENTER_SPEED*dt;if(enemy.x<=enemy.combatX){enemy.x=enemy.combatX;enemy.state="idle";}return;}if(enemy.state==="idle"){enemy.throwTimer=Math.max(0,enemy.throwTimer-dt);if(enemy.throwTimer<=0){enemy.state="telegraph";enemy.stateTimer=CONFIG.ENEMY.TELEGRAPH;}return;}if(enemy.state==="telegraph"&&enemy.stateTimer<=0){createIncomingBall(enemy);enemy.state="recovery";enemy.stateTimer=CONFIG.ENEMY.RECOVERY;return;}if(enemy.state==="recovery"&&enemy.stateTimer<=0){enemy.state="idle";enemy.throwTimer=randomRange(CONFIG.ENEMY.THROW_INTERVAL_MIN,CONFIG.ENEMY.THROW_INTERVAL_MAX);}}
function createIncomingBall(enemy){const p=gameState.player,dir=safeDirection(p.x-enemy.x,p.y-enemy.y,-1,0);gameState.incomingBalls.push({id:nextId(),type:"incomingBall",active:true,ownerEnemyId:enemy.id,ballType:"normal",x:enemy.x-enemy.radius,y:enemy.y,vx:dir.x*CONFIG.BALL.SPEED,vy:dir.y*CONFIG.BALL.SPEED,radius:CONFIG.BALL.RADIUS,damage:CONFIG.BALL.DAMAGE,returnPower:CONFIG.BALL.RETURN_POWER,catchable:true,processed:false});burst(enemy.x-enemy.radius,enemy.y,CONFIG.COLORS.orange,CONFIG.FX.PARTICLE_COUNT);}
function updateIncomingBalls(dt){const p=gameState.player;for(const ball of gameState.incomingBalls){if(!ball.active)continue;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;addTrail(ball.x,ball.y,CONFIG.COLORS.orange,ball.radius);if(overlaps(ball,p,ball.radius,CONFIG.PLAYER.HITBOX)&&p.invincibilityTimer<=0)damagePlayer(ball);if(outsideCleanup(ball))ball.active=false;}}

function isBallInsideCatchField(ball){const p=gameState.player,centerX=p.x+p.facingX*CONFIG.CATCH.OFFSET,centerY=p.y+p.facingY*CONFIG.CATCH.OFFSET,dx=ball.x-p.x,dy=ball.y-p.y,dist=length(dx,dy);if(dist<=Number.EPSILON)return true;const dot=(dx/dist)*p.facingX+(dy/dist)*p.facingY;return dot>=CONFIG.CATCH.FORWARD_DOT&&((ball.x-centerX)**2+(ball.y-centerY)**2)<=(CONFIG.CATCH.RADIUS+ball.radius)**2;}
function isJustCatch(){const since=gameState.elapsedTime-gameState.input.catchPressedAt;return since>=0&&since<=CONFIG.CATCH.JUST_WINDOW;}
function checkCatchCollisions(){const p=gameState.player;if(p.actionState!=="catching"||!gameState.input.catchHeld)return;for(const ball of gameState.incomingBalls){if(!ball.active||!ball.catchable||ball.processed||!isBallInsideCatchField(ball))continue;const just=isJustCatch();if(gameState.heldBall){if(just)handleFullHandJustCatch(ball);continue;}if(just)handleJustCatch(ball);else handleNormalCatch(ball);break;}}
function captureData(ball,wasJustCaught){return{ballType:ball.ballType,sourceEnemyId:ball.ownerEnemyId,damage:ball.damage,returnPower:ball.returnPower,capturedAt:gameState.elapsedTime,wasJustCaught};}
function consumeCatch(ball){ball.active=false;ball.processed=true;gameState.input.catchPressedAt=-Infinity;}
function handleNormalCatch(ball){consumeCatch(ball);gameState.heldBall=captureData(ball,false);setPlayerAction("catchRecovery",CONFIG.CATCH.NORMAL_RECOVERY);gameState.score+=CONFIG.SCORE.NORMAL_CATCH;addCombo(CONFIG.COMBO.NORMAL_CATCH);catchFeedback(false);}
function handleJustCatch(ball){consumeCatch(ball);gameState.heldBall=captureData(ball,true);setPlayerAction("catchRecovery",CONFIG.CATCH.JUST_RECOVERY);gameState.player.invincibilityTimer=Math.max(gameState.player.invincibilityTimer,CONFIG.CATCH.INVINCIBILITY);gameState.returnRush={timer:CONFIG.CATCH.RUSH_WINDOW,sourceEnemyId:ball.ownerEnemyId};gameState.score+=CONFIG.SCORE.JUST_CATCH;addCombo(CONFIG.COMBO.JUST_CATCH);catchFeedback(true);}
function handleFullHandJustCatch(ball){consumeCatch(ball);const source=enemyById(ball.ownerEnemyId);const target=source&&isValidTarget(source)?source:validateTarget();createReturnedBall(ball, target, true);setPlayerAction("throwing",CONFIG.THROW.RUSH_RECOVERY);gameState.player.invincibilityTimer=Math.max(gameState.player.invincibilityTimer,CONFIG.CATCH.INVINCIBILITY);addCombo(CONFIG.COMBO.RUSH);gameState.returnRush=null;strongText("FULL-HAND RETURN",gameState.player.x+CONFIG.CATCH.OFFSET,gameState.player.y-CONFIG.CATCH.RADIUS,CONFIG.COLORS.cyan);returnFeedback(true);}
function catchFeedback(just){const p=gameState.player,amount=just?CONFIG.FX.STRONG_PARTICLE_COUNT:CONFIG.FX.PARTICLE_COUNT,color=just?CONFIG.COLORS.cyan:CONFIG.COLORS.white;burst(p.x+CONFIG.CATCH.OFFSET,p.y,color,amount);ring(p.x+CONFIG.CATCH.OFFSET,p.y,color,just);gameState.hitStop=just?CONFIG.CATCH.JUST_HIT_STOP:CONFIG.CATCH.HIT_STOP;gameState.screenFlash=just?CONFIG.FX.FLASH_JUST:CONFIG.FX.FLASH_NORMAL;gameState.screenShake=Math.max(gameState.screenShake,just?CONFIG.FX.SHAKE_BIG:CONFIG.FX.SHAKE_SMALL);strongText(just?"JUST CATCH":"CAUGHT",p.x+CONFIG.CATCH.OFFSET,p.y-CONFIG.CATCH.RADIUS,color);}

function isValidTarget(enemy){return Boolean(enemy&&enemy.active&&enemy.state!=="defeated"&&enemy.x>=-CONFIG.TARGET.SCREEN_MARGIN&&enemy.x<=CONFIG.WIDTH+CONFIG.TARGET.SCREEN_MARGIN);}
function enemyById(id){return gameState.enemies.find(enemy=>enemy.id===id)||null;}
function validateTarget(){const current=enemyById(gameState.targetEnemyId);if(isValidTarget(current))return current;gameState.targetEnemyId=null;return selectAutomaticTarget();}
function selectAutomaticTarget(){const p=gameState.player;let best=null,bestScore=-Infinity;for(const enemy of gameState.enemies){if(!isValidTarget(enemy))continue;const dx=enemy.x-p.x,dy=enemy.y-p.y,dist=Math.max(Number.EPSILON,length(dx,dy)),direction=(dx/dist)*p.facingX+(dy/dist)*p.facingY;const score=-dist*CONFIG.TARGET.DISTANCE_WEIGHT+direction*CONFIG.TARGET.DIRECTION_WEIGHT+(direction>0?CONFIG.TARGET.FRONT_BONUS:0);if(score>bestScore){bestScore=score;best=enemy;}}gameState.targetEnemyId=best?best.id:null;return best;}
function requestThrow(){if(gameState.phase==="playing")gameState.input.throwRequested=true;}
function canThrow(){const state=gameState.player.actionState;return Boolean(gameState.heldBall&&!state.includes("hurt")&&state!=="throwing"&&state!=="catchRecovery");}
function throwHeldBall(){if(!canThrow())return;const held=gameState.heldBall;const rush=Boolean(gameState.returnRush&&held.wasJustCaught&&gameState.returnRush.timer>0);if(rush){performReturnRush(held);return;}const target=validateTarget();createReturnedBall(held,target,false);gameState.heldBall=null;setPlayerAction("throwing",CONFIG.THROW.RECOVERY);gameState.player.recoilTimer=CONFIG.THROW.RECOIL;returnFeedback(false);}
function performReturnRush(held){const source=enemyById(gameState.returnRush.sourceEnemyId);const target=isValidTarget(source)?source:validateTarget();createReturnedBall(held,target,true);gameState.heldBall=null;gameState.returnRush=null;setPlayerAction("throwing",CONFIG.THROW.RUSH_RECOVERY);gameState.player.recoilTimer=CONFIG.THROW.RECOIL;addCombo(CONFIG.COMBO.RUSH);strongText("RETURN RUSH",gameState.player.x+CONFIG.THROW.SPAWN_OFFSET,gameState.player.y-CONFIG.CATCH.RADIUS,CONFIG.COLORS.cyan);returnFeedback(true);}
function createReturnedBall(source,target,justReturn){const p=gameState.player,dir=target?safeDirection(target.x-p.x,target.y-p.y):{x:p.facingX,y:p.facingY},speed=justReturn?CONFIG.BALL.RUSH_SPEED:CONFIG.BALL.RETURN_SPEED,baseDamage=source.returnPower*CONFIG.BALL.RETURN_DAMAGE;const ball={id:nextId(),type:"returnedBall",active:true,sourceBallType:source.ballType||"normal",sourceEnemyId:source.sourceEnemyId??source.ownerEnemyId,targetEnemyId:target?target.id:null,x:p.x+dir.x*CONFIG.THROW.SPAWN_OFFSET,y:p.y+dir.y*CONFIG.THROW.SPAWN_OFFSET,vx:dir.x*speed,vy:dir.y*speed,radius:CONFIG.BALL.RADIUS,damage:baseDamage*(justReturn?CONFIG.BALL.JUST_DAMAGE_MULTIPLIER:1),justReturn,alreadyHitIds:new Set()};gameState.returnedBalls.push(ball);return ball;}
function returnFeedback(strong){const p=gameState.player,color=strong?CONFIG.COLORS.cyan:CONFIG.COLORS.orange;burst(p.x+CONFIG.THROW.SPAWN_OFFSET,p.y,color,strong?CONFIG.FX.STRONG_PARTICLE_COUNT:CONFIG.FX.PARTICLE_COUNT);gameState.screenShake=Math.max(gameState.screenShake,strong?CONFIG.FX.SHAKE_BIG:CONFIG.FX.SHAKE_SMALL);gameState.screenFlash=strong?CONFIG.FX.FLASH_JUST:CONFIG.FX.FLASH_NORMAL;}
function updateReturnedBalls(dt){for(const ball of gameState.returnedBalls){if(!ball.active)continue;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;addTrail(ball.x,ball.y,ball.justReturn?CONFIG.COLORS.cyan:CONFIG.COLORS.white,ball.radius);for(const enemy of gameState.enemies){if(!ball.active||!isValidTarget(enemy)||ball.alreadyHitIds.has(enemy.id))continue;if(overlaps(ball,enemy)){ball.alreadyHitIds.add(enemy.id);damageEnemy(enemy,ball.damage,ball.justReturn);if(!CONFIG.BALL.PENETRATION)ball.active=false;}}if(outsideCleanup(ball))ball.active=false;}}
function damageEnemy(enemy,damage,justReturn){if(!isValidTarget(enemy))return;enemy.hp=Math.max(0,enemy.hp-damage);enemy.hitFlashTimer=CONFIG.ENEMY.HIT_FLASH;enemy.throwTimer+=CONFIG.ENEMY.HIT_DELAY;enemy.knockback=CONFIG.ENEMY.KNOCKBACK;gameState.score+=justReturn?CONFIG.SCORE.RUSH_HIT:CONFIG.SCORE.RETURN_HIT;addCombo(justReturn?CONFIG.COMBO.RUSH:CONFIG.COMBO.RETURN_HIT);burst(enemy.x,enemy.y,justReturn?CONFIG.COLORS.cyan:CONFIG.COLORS.orange,justReturn?CONFIG.FX.STRONG_PARTICLE_COUNT:CONFIG.FX.PARTICLE_COUNT);ring(enemy.x,enemy.y,justReturn?CONFIG.COLORS.cyan:CONFIG.COLORS.orange,justReturn);strongText(`+${justReturn?CONFIG.SCORE.RUSH_HIT:CONFIG.SCORE.RETURN_HIT}`,enemy.x,enemy.y-enemy.radius,CONFIG.COLORS.white);if(enemy.hp<=0)destroyEnemy(enemy);}
function destroyEnemy(enemy){if(enemy.state==="defeated")return;enemy.state="defeated";enemy.stateTimer=CONFIG.ENEMY.DEFEAT_TIME;gameState.encounter.defeatedEnemies++;gameState.score+=CONFIG.SCORE.DEFEAT;addCombo(CONFIG.COMBO.DEFEAT);burst(enemy.x,enemy.y,CONFIG.COLORS.orange,CONFIG.FX.STRONG_PARTICLE_COUNT);strongText(`K.O. +${CONFIG.SCORE.DEFEAT}`,enemy.x,enemy.y-CONFIG.CATCH.RADIUS,CONFIG.COLORS.orange);if(gameState.targetEnemyId===enemy.id)gameState.targetEnemyId=null;}

function damagePlayer(ball){if(gameState.player.invincibilityTimer>0||!ball.active)return;ball.active=false;const p=gameState.player;p.hp=Math.max(0,p.hp-ball.damage);p.invincibilityTimer=CONFIG.PLAYER.INVINCIBILITY;p.hitFlashTimer=CONFIG.ENEMY.HIT_FLASH;setPlayerAction("hurt",CONFIG.PLAYER.HURT_DURATION);gameState.combo=0;gameState.comboTimer=0;gameState.returnRush=null;dropHeldBall();burst(p.x,p.y,CONFIG.COLORS.red,CONFIG.FX.STRONG_PARTICLE_COUNT);strongText("HIT",p.x,p.y-CONFIG.CATCH.RADIUS,CONFIG.COLORS.red);gameState.screenShake=CONFIG.FX.SHAKE_BIG;gameState.screenFlash=CONFIG.FX.FLASH_JUST;}
function dropHeldBall(){if(!gameState.heldBall)return;gameState.heldBall=null;burst(gameState.player.x,gameState.player.y,CONFIG.COLORS.orange,CONFIG.FX.PARTICLE_COUNT);strongText("BALL LOST",gameState.player.x,gameState.player.y+CONFIG.CATCH.RADIUS,CONFIG.COLORS.orange);}
function setPlayerAction(state,timer){gameState.player.actionState=state;gameState.player.actionTimer=timer;}
function addCombo(amount){gameState.combo+=amount;gameState.comboTimer=CONFIG.COMBO.TIMEOUT;}
function updateCombo(dt){if(gameState.combo<=0)return;gameState.comboTimer=Math.max(0,gameState.comboTimer-dt);if(gameState.comboTimer<=0)gameState.combo=0;}
function outsideCleanup(entity){const m=CONFIG.BALL.CLEANUP_MARGIN;return entity.x<-m||entity.x>CONFIG.WIDTH+m||entity.y<-m||entity.y>CONFIG.HEIGHT+m;}

function burst(x,y,color,count){for(let i=0;i<count;i++){const angle=Math.random()*CONFIG.TAU,speed=Math.random()*CONFIG.FX.PARTICLE_SPEED;gameState.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:CONFIG.FX.PARTICLE_LIFE,maxLife:CONFIG.FX.PARTICLE_LIFE,color,size:randomRange(2,6)});}}
function ring(x,y,color,strong){gameState.rings.push({x,y,color,life:CONFIG.FX.RING_LIFE,maxLife:CONFIG.FX.RING_LIFE,strong});}
function strongText(text,x,y,color){gameState.floatingTexts.push({text,x,y,color,life:CONFIG.FX.TEXT_LIFE,maxLife:CONFIG.FX.TEXT_LIFE});}
function addTrail(x,y,color,size){gameState.trails.push({x,y,color,size,life:CONFIG.FX.TRAIL_LIFE,maxLife:CONFIG.FX.TRAIL_LIFE});}
function updateEffects(dt){gameState.screenShake=Math.max(0,gameState.screenShake-CONFIG.FX.SHAKE_BIG*dt);gameState.screenFlash=Math.max(0,gameState.screenFlash-dt);for(const particle of gameState.particles){particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.life=Math.max(0,particle.life-dt);}for(const item of [...gameState.floatingTexts,...gameState.rings,...gameState.trails])item.life=Math.max(0,item.life-dt);for(const text of gameState.floatingTexts)text.y-=CONFIG.FX.PARTICLE_SPEED*.15*dt;}
function cleanupEntities(){gameState.enemies=gameState.enemies.filter(e=>e.active);gameState.incomingBalls=gameState.incomingBalls.filter(b=>b.active);gameState.returnedBalls=gameState.returnedBalls.filter(b=>b.active);gameState.particles=gameState.particles.filter(p=>p.life>0);gameState.floatingTexts=gameState.floatingTexts.filter(t=>t.life>0);gameState.rings=gameState.rings.filter(r=>r.life>0);gameState.trails=gameState.trails.filter(t=>t.life>0);}
function triggerClear(){if(gameState.phase!=="playing")return;gameState.result="clear";gameState.dom["result-kicker"].textContent="RETURN PROTOCOL COMPLETE";gameState.dom["result-title"].textContent="CLEAR";finishGame();}
function triggerDefeat(){if(gameState.phase!=="playing")return;gameState.result="defeat";gameState.dom["result-kicker"].textContent="DRILL TERMINATED";gameState.dom["result-title"].textContent="GAME OVER";finishGame();}
function finishGame(){gameState.dom["final-score"].textContent=String(gameState.score).padStart(CONFIG.VIEW.SCORE_DIGITS,"0");setPhase("gameover");}
function syncHud(){const p=gameState.player;gameState.dom.score.textContent=String(gameState.score).padStart(CONFIG.VIEW.SCORE_DIGITS,"0");gameState.dom.combo.textContent=gameState.combo>0?`x${gameState.combo}`:"—";gameState.dom.hp.textContent=p?Array.from({length:p.maxHp},(_,i)=>i<p.hp?CONFIG.VIEW.HP_GLYPH:"○").join(" "):"—";gameState.dom.held.textContent=gameState.heldBall?(gameState.returnRush?"RUSH READY":"BALL READY"):"EMPTY";gameState.dom.held.classList.toggle("ready",Boolean(gameState.heldBall));gameState.dom.progress.textContent=`${gameState.encounter.defeatedEnemies} / ${gameState.encounter.targetDefeats}`;}

function render(){const ctx=gameState.ctx;ctx.save();ctx.clearRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);const shake=gameState.screenShake;ctx.translate(randomRange(-shake,shake),randomRange(-shake,shake));renderBackground(ctx);renderGround(ctx);renderEnemyTelegraphs(ctx);renderTargetMarker(ctx);renderTrails(ctx);renderEnemies(ctx);renderIncomingBalls(ctx);renderReturnedBalls(ctx);renderCatchField(ctx);renderHeldBall(ctx);renderPlayer(ctx);renderParticles(ctx);renderFloatingTexts(ctx);renderPlayerHitbox(ctx);ctx.restore();if(gameState.screenFlash>0){ctx.save();ctx.globalAlpha=clamp(gameState.screenFlash/CONFIG.FX.FLASH_JUST,0,.32);ctx.fillStyle=CONFIG.COLORS.white;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);ctx.restore();}}
function renderBackground(ctx){const gradient=ctx.createLinearGradient(0,0,0,CONFIG.HEIGHT);gradient.addColorStop(0,CONFIG.COLORS.sky);gradient.addColorStop(1,CONFIG.COLORS.sky2);ctx.fillStyle=gradient;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);ctx.fillStyle="#09131c";ctx.fillRect(0,78,CONFIG.WIDTH,150);for(let i=0;i<CONFIG.VIEW.LIGHT_COUNT;i++){const spacing=CONFIG.WIDTH/CONFIG.VIEW.LIGHT_COUNT,x=(i*spacing-gameState.elapsedTime*CONFIG.VIEW.SCROLL_SPEED)%(CONFIG.WIDTH+spacing);ctx.fillStyle=i%3===0?CONFIG.COLORS.orange:CONFIG.COLORS.cyan;ctx.globalAlpha=.22;ctx.fillRect(x,105,32,4);ctx.globalAlpha=1;}ctx.fillStyle="#132432";for(let x=0;x<CONFIG.WIDTH;x+=CONFIG.VIEW.GRID_GAP)ctx.fillRect(x,215,CONFIG.VIEW.GRID_GAP*.55,72);ctx.fillStyle="#243946";ctx.fillRect(0,286,CONFIG.WIDTH,3);}
function renderGround(ctx){ctx.fillStyle=CONFIG.COLORS.ground;ctx.beginPath();ctx.moveTo(0,300);ctx.lineTo(CONFIG.WIDTH,300);ctx.lineTo(CONFIG.WIDTH,CONFIG.HEIGHT);ctx.lineTo(0,CONFIG.HEIGHT);ctx.fill();ctx.strokeStyle=CONFIG.COLORS.line;ctx.lineWidth=1;ctx.globalAlpha=.5;for(let y=CONFIG.VIEW.GROUND_Y;y>300;y-=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CONFIG.WIDTH,y);ctx.stroke();}for(let x=-CONFIG.WIDTH;x<CONFIG.WIDTH*2;x+=CONFIG.VIEW.GRID_GAP){ctx.beginPath();ctx.moveTo(CONFIG.WIDTH/2,300);ctx.lineTo(x,CONFIG.HEIGHT);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle=CONFIG.COLORS.orange;ctx.lineWidth=2;ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(CONFIG.PLAYER.MOVE_MAX_X,305);ctx.lineTo(CONFIG.PLAYER.MOVE_MAX_X,CONFIG.HEIGHT);ctx.stroke();ctx.setLineDash([]);}
function renderPlayer(ctx){const p=gameState.player;if(!p)return;const blink=p.invincibilityTimer>0&&Math.floor(gameState.elapsedTime*14)%2===0;ctx.save();ctx.globalAlpha=blink?.4:1;ctx.translate(p.x-(p.recoilTimer>0?8:0),p.y);ctx.fillStyle="#05090d";ctx.beginPath();ctx.ellipse(0,p.radius+16,30,9,0,0,CONFIG.TAU);ctx.fill();ctx.fillStyle=p.hitFlashTimer>0?CONFIG.COLORS.white:"#e7f1ed";ctx.beginPath();ctx.arc(0,0,p.radius,0,CONFIG.TAU);ctx.fill();ctx.fillStyle="#172b37";ctx.fillRect(-18,1,36,20);ctx.fillStyle=CONFIG.COLORS.cyan;ctx.fillRect(-13,7,26,5);ctx.fillStyle="#0b141b";ctx.beginPath();ctx.arc(6,-5,4,0,CONFIG.TAU);ctx.fill();const gloveX=p.actionState==="catching"?34:p.actionState==="throwing"?38:24;ctx.fillStyle=CONFIG.COLORS.orange;ctx.beginPath();ctx.arc(gloveX,-2,12,0,CONFIG.TAU);ctx.fill();ctx.strokeStyle="#ffe0bc";ctx.lineWidth=3;ctx.beginPath();ctx.arc(gloveX+2,-3,7,-1.7,1.7);ctx.stroke();ctx.restore();}
function renderCatchField(ctx){const p=gameState.player;if(!p||p.actionState!=="catching")return;const x=p.x+p.facingX*CONFIG.CATCH.OFFSET,y=p.y+p.facingY*CONFIG.CATCH.OFFSET,just=isJustCatch();ctx.save();ctx.strokeStyle=just?CONFIG.COLORS.cyan:CONFIG.COLORS.white;ctx.fillStyle=just?"#63f5e51d":"#edf8f50d";ctx.lineWidth=just?4:2;ctx.setLineDash([9,7]);ctx.beginPath();ctx.arc(x,y,CONFIG.CATCH.RADIUS,0,CONFIG.TAU);ctx.fill();ctx.stroke();ctx.setLineDash([]);ctx.restore();}
function renderHeldBall(ctx){if(!gameState.heldBall||!gameState.player)return;const p=gameState.player,angle=gameState.elapsedTime*4,x=p.x-5+Math.cos(angle)*7,y=p.y-35+Math.sin(angle)*4;drawBall(ctx,x,y,CONFIG.BALL.RADIUS,gameState.returnRush?CONFIG.COLORS.cyan:CONFIG.COLORS.orange,true);}
function renderEnemies(ctx){for(const e of gameState.enemies){ctx.save();ctx.translate(e.x+e.knockback,e.y);if(e.state==="defeated")ctx.scale(1+e.stateTimer,.5+e.stateTimer);ctx.fillStyle="#02060a";ctx.beginPath();ctx.ellipse(0,e.radius+15,34,9,0,0,CONFIG.TAU);ctx.fill();ctx.fillStyle=e.hitFlashTimer>0?CONFIG.COLORS.white:"#9eabb0";ctx.beginPath();ctx.arc(0,0,e.radius,0,CONFIG.TAU);ctx.fill();ctx.fillStyle="#1a2730";ctx.fillRect(-e.radius,3,e.radius*2,18);ctx.fillStyle=CONFIG.COLORS.red;ctx.fillRect(-17,8,34,5);ctx.fillStyle="#0a1015";ctx.fillRect(-15,-8,7,5);ctx.fillRect(8,-8,7,5);ctx.fillStyle=CONFIG.COLORS.orange;ctx.beginPath();ctx.arc(-e.radius+2,1,9,0,CONFIG.TAU);ctx.fill();ctx.restore();if(e.state!=="defeated"){const width=e.radius*2;ctx.fillStyle="#071017";ctx.fillRect(e.x-width/2,e.y-e.radius-14,width,5);ctx.fillStyle=CONFIG.COLORS.red;ctx.fillRect(e.x-width/2,e.y-e.radius-14,width*(e.hp/e.maxHp),5);}}}
function renderEnemyTelegraphs(ctx){for(const e of gameState.enemies){if(e.state!=="telegraph")continue;const progress=1-e.stateTimer/CONFIG.ENEMY.TELEGRAPH;ctx.save();ctx.strokeStyle=CONFIG.COLORS.orange;ctx.lineWidth=3;ctx.globalAlpha=.4+progress*.6;ctx.beginPath();ctx.arc(e.x,e.y,e.radius+14-progress*9,0,CONFIG.TAU);ctx.stroke();ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(gameState.player.x,gameState.player.y);ctx.strokeStyle="#ff9e4555";ctx.setLineDash([8,10]);ctx.stroke();ctx.restore();}}
function renderIncomingBalls(ctx){for(const ball of gameState.incomingBalls)drawBall(ctx,ball.x,ball.y,ball.radius,CONFIG.COLORS.orange,true);}
function renderReturnedBalls(ctx){for(const ball of gameState.returnedBalls)drawBall(ctx,ball.x,ball.y,ball.radius,ball.justReturn?CONFIG.COLORS.cyan:CONFIG.COLORS.white,true);}
function drawBall(ctx,x,y,radius,color,glow){ctx.save();if(glow){ctx.shadowColor=color;ctx.shadowBlur=14;}ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,radius,0,CONFIG.TAU);ctx.fill();ctx.strokeStyle="#17222a";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,radius*.58,-1.2,1.3);ctx.stroke();ctx.restore();}
function renderTargetMarker(ctx){const target=enemyById(gameState.targetEnemyId);if(!isValidTarget(target))return;const pulse=Math.sin(gameState.elapsedTime*6)*3;ctx.save();ctx.strokeStyle=CONFIG.COLORS.cyan;ctx.lineWidth=2;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(target.x,target.y,target.radius+12+pulse,0,CONFIG.TAU);ctx.stroke();ctx.fillStyle=CONFIG.COLORS.cyan;ctx.font="800 9px ui-monospace";ctx.textAlign="center";ctx.fillText("TARGET",target.x,target.y-target.radius-20);ctx.restore();}
function renderTrails(ctx){ctx.save();for(const trail of gameState.trails){ctx.globalAlpha=trail.life/trail.maxLife*.55;ctx.fillStyle=trail.color;ctx.beginPath();ctx.arc(trail.x,trail.y,trail.size*(trail.life/trail.maxLife),0,CONFIG.TAU);ctx.fill();}ctx.restore();}
function renderParticles(ctx){ctx.save();for(const particle of gameState.particles){ctx.globalAlpha=particle.life/particle.maxLife;ctx.fillStyle=particle.color;ctx.fillRect(particle.x-particle.size/2,particle.y-particle.size/2,particle.size,particle.size);}for(const item of gameState.rings){const progress=1-item.life/item.maxLife;ctx.globalAlpha=1-progress;ctx.strokeStyle=item.color;ctx.lineWidth=item.strong?5:3;ctx.beginPath();ctx.arc(item.x,item.y,10+progress*(item.strong?75:45),0,CONFIG.TAU);ctx.stroke();}ctx.restore();}
function renderFloatingTexts(ctx){ctx.save();ctx.textAlign="center";ctx.textBaseline="middle";for(const text of gameState.floatingTexts){ctx.globalAlpha=text.life/text.maxLife;ctx.fillStyle=text.color;ctx.strokeStyle=CONFIG.COLORS.shadow;ctx.lineWidth=5;ctx.font="900 18px Impact, sans-serif";ctx.strokeText(text.text,text.x,text.y);ctx.fillText(text.text,text.x,text.y);}ctx.restore();}
function renderPlayerHitbox(ctx){const p=gameState.player;if(!p)return;ctx.save();ctx.globalAlpha=.65;ctx.strokeStyle=CONFIG.COLORS.cyan;ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,CONFIG.PLAYER.HITBOX,0,CONFIG.TAU);ctx.stroke();ctx.fillStyle=CONFIG.COLORS.white;ctx.beginPath();ctx.arc(p.x,p.y,2,0,CONFIG.TAU);ctx.fill();ctx.restore();}
function gameLoop(timestamp){if(!gameState.lastTimestamp)gameState.lastTimestamp=timestamp;const dt=Math.min(CONFIG.MAX_DELTA,(timestamp-gameState.lastTimestamp)/1000);gameState.lastTimestamp=timestamp;update(dt);render();gameState.animationFrame=requestAnimationFrame(gameLoop);}
function initialize(){cacheDom();bindEvents();resetGame();setPhase("start");if(gameState.animationFrame===null)gameState.animationFrame=requestAnimationFrame(gameLoop);}

document.addEventListener("DOMContentLoaded",initialize,{once:true});
