"use strict";

const CONFIG = Object.freeze({
  WIDTH:960, HEIGHT:540, TAU:Math.PI*2, MAX_DELTA:.033,
  COLORS:{sky:"#07131f",sky2:"#10283a",ground:"#101c23",line:"#35515c",cyan:"#63f5e5",orange:"#ff9e45",red:"#ff626b",white:"#edf8f5",muted:"#78909a",shadow:"#02070b",break:"#ffe06b"},
  PLAYER:{X:154,Y:330,RADIUS:22,HITBOX:13,HP:4,SPEED:350,INVINCIBILITY:1,HURT_TIME:.34,MIN_X:42,MAX_X:430,MIN_Y:128,MAX_Y:468},
  CATCH:{RADIUS:62,OFFSET:40,JUST_WINDOW:.2,NORMAL_RECOVERY:.2,JUST_RECOVERY:.03,RUSH_WINDOW:.75,JUST_SLOW:.08},
  THROW:{RECOVERY:.38,RUSH_RECOVERY:.12,OFFSET:36,NORMAL_SPEED:650,JUST_SPEED:860},
  ENEMY:{RADIUS:28,MAX_ACTIVE:2,TOTAL:4,ENTER_SPEED:150,SPAWN_X:1010,X_MIN:720,X_GAP:105,Y_MIN:180,Y_MAX:430,SPAWN_INTERVAL:2,FIRST_SPAWN:.25,IDLE_MIN:1.25,IDLE_MAX:2.05,TELEGRAPH:1.05,RECOVERY:.95,DEFEAT_TIME:.55,KNOCKBACK:64,MAX_BREAK:100,INITIAL_BREAK:0,INITIAL_RECOVERY_DELAY:0,INITIAL_BREAK_TIMER:0},
  BREAK:{NORMAL_DAMAGE:28,RECOVERY_HIT_MULTIPLIER:1.45,JUST_DAMAGE:62,COUNTER_DAMAGE:76,RALLY_BONUS_PER_COUNT:11,MAX_RALLY_BONUS:33,RECOVERY_DELAY:2.4,RECOVERY_PER_SECOND:5,BROKEN_DURATION:5.5,FIRST_BROKEN_DURATION:7,FAILED_BREAK_RETAIN_RATIO:.58,FINISH_SPEED:1250,FINISH_RECOVERY:.08,COUNTER_WINDOW:.32,HIGH_RATIO:.72,NEAR_FULL_RATIO:.82},
  TARGET:{VERTICAL_WEIGHT:4.5,BROKEN_BONUS:900,NEAR_BREAK_BONUS:380,VULNERABLE_BONUS:190,DISTANCE_WEIGHT:.08,SWITCH_THRESHOLD:55,LOCK_MIN_TIME:.3,ALIGNED_Y:100},
  BALL:{RADIUS:11,INCOMING_SPEED:285,CLEANUP_MARGIN:110,RALLY_SPEED_GAIN:.14,MAX_SPEED:780,MAX_RALLY_COUNT:5},
  BATTER:{SPAWN_EVERY:3,SWING_DISTANCE:245,RETURN_DELAY:.22,SPEED_MULTIPLIER:1.14},
  SCORE:{CATCH:50,JUST_CATCH:175,HIT:100,JUST_HIT:250,COUNTER:300,BREAK:400,FINISH:900,KO:500,RALLY:80},
  FX:{PARTICLES:10,STRONG_PARTICLES:25,LIFE:.5,TEXT_LIFE:.85,TRAIL_LIFE:.18,SHAKE:4,BIG_SHAKE:10,HIT_STOP:.06,COUNTER_STOP:.13,FINISH_STOP:.2,HIT_STOP_SCALE:.12,DIM_TIME:.3,FINISH_LINE_TIME:.35},
  VIEW:{GROUND_Y:475,GRID:80,SCORE_DIGITS:6}
});

const gameState={
  phase:"start",result:null,elapsedTime:0,frame:0,score:0,combo:0,comboTimer:0,player:null,enemies:[],incomingBalls:[],returnedBalls:[],particles:[],texts:[],trails:[],heldBall:null,targetEnemyId:null,targetLockTimer:0,nextEntityId:1,spawned:0,defeated:0,spawnTimer:0,
  input:{keys:new Set(),pointerX:CONFIG.PLAYER.X,pointerY:CONFIG.PLAYER.Y,pointerActive:false,keyboardCatch:false,pointerCatch:false,catchHeld:false,catchPressedAt:-Infinity,throwRequested:false},
  tutorial:null,screenShake:0,screenFlash:0,backgroundDim:0,hitStop:0,finishEffect:null,lastTimestamp:0,animationFrame:null,listenersBound:false,ctx:null,dom:{}
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const random=(a,b)=>a+Math.random()*(b-a);
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const direction=(x,y)=>{const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m};};
const overlaps=(a,b,ar=a.radius,br=b.radius)=>(a.x-b.x)**2+(a.y-b.y)**2<=(ar+br)**2;
const nextId=()=>gameState.nextEntityId++;

function cacheDom(){["game-canvas","score","combo","hp","held","progress","start-overlay","result-overlay","result-kicker","result-title","final-score","start-button","restart-button"].forEach(id=>gameState.dom[id]=document.getElementById(id));gameState.ctx=gameState.dom["game-canvas"].getContext("2d");}
function createPlayer(){return{x:CONFIG.PLAYER.X,y:CONFIG.PLAYER.Y,radius:CONFIG.PLAYER.RADIUS,hp:CONFIG.PLAYER.HP,action:"normal",timer:0,invincible:0};}
function resetGame(){Object.assign(gameState,{result:null,elapsedTime:0,frame:0,score:0,combo:0,comboTimer:0,player:createPlayer(),enemies:[],incomingBalls:[],returnedBalls:[],particles:[],texts:[],trails:[],heldBall:null,targetEnemyId:null,targetLockTimer:0,nextEntityId:1,spawned:0,defeated:0,spawnTimer:CONFIG.ENEMY.FIRST_SPAWN,tutorial:{caught:false,firstBreak:false},screenShake:0,screenFlash:0,backgroundDim:0,hitStop:0,finishEffect:null});gameState.input.keys.clear();Object.assign(gameState.input,{pointerActive:false,keyboardCatch:false,pointerCatch:false,catchHeld:false,catchPressedAt:-Infinity,throwRequested:false});syncHud();}
function setPhase(phase){gameState.phase=phase;gameState.dom["start-overlay"].classList.toggle("hidden",phase!=="start");gameState.dom["result-overlay"].classList.toggle("hidden",phase!=="gameover");}
function startGame(){resetGame();setPhase("playing");}
function bindEvents(){if(gameState.listenersBound)return;gameState.listenersBound=true;const canvas=gameState.dom["game-canvas"];
  const refreshCatch=()=>{const held=gameState.input.keyboardCatch||gameState.input.pointerCatch;if(held&&!gameState.input.catchHeld&&gameState.phase==="playing")gameState.input.catchPressedAt=gameState.elapsedTime;gameState.input.catchHeld=held;};
  const pointer=e=>{const r=canvas.getBoundingClientRect();gameState.input.pointerX=(e.clientX-r.left)*CONFIG.WIDTH/r.width;gameState.input.pointerY=(e.clientY-r.top)*CONFIG.HEIGHT/r.height;gameState.input.pointerActive=true;};
  addEventListener("keydown",e=>{if(["Space","ShiftLeft","ShiftRight","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();gameState.input.keys.add(e.code);if(e.code.startsWith("Shift")){gameState.input.keyboardCatch=true;refreshCatch();}if(e.code==="Space"&&!e.repeat)gameState.input.throwRequested=true;});
  addEventListener("keyup",e=>{gameState.input.keys.delete(e.code);if(e.code.startsWith("Shift")){gameState.input.keyboardCatch=false;refreshCatch();}});canvas.addEventListener("pointermove",pointer);canvas.addEventListener("pointerdown",e=>{e.preventDefault();pointer(e);if(e.button===0){gameState.input.pointerCatch=true;refreshCatch();}else if(e.button===2)gameState.input.throwRequested=true;});canvas.addEventListener("pointerup",e=>{if(e.button===0){gameState.input.pointerCatch=false;refreshCatch();}});canvas.addEventListener("contextmenu",e=>e.preventDefault());gameState.dom["start-button"].addEventListener("click",startGame);gameState.dom["restart-button"].addEventListener("click",startGame);addEventListener("blur",()=>{gameState.input.keys.clear();gameState.input.keyboardCatch=gameState.input.pointerCatch=false;refreshCatch();});
}
function createEnemy(){const slot=gameState.enemies.filter(e=>e.active&&e.state!=="defeated").length;const first=gameState.spawned===0;return{id:nextId(),active:true,type:gameState.spawned>0&&gameState.spawned%CONFIG.BATTER.SPAWN_EVERY===0?"batter":"basic",x:CONFIG.ENEMY.SPAWN_X,targetX:CONFIG.ENEMY.X_MIN+slot*CONFIG.ENEMY.X_GAP,y:first?285:random(CONFIG.ENEMY.Y_MIN,CONFIG.ENEMY.Y_MAX),radius:CONFIG.ENEMY.RADIUS,state:"entering",stateTimer:0,vulnerable:false,flash:0,knockback:0,actionSerial:0,throwResolvedSerial:-1,breakValue:CONFIG.ENEMY.INITIAL_BREAK,maxBreak:CONFIG.ENEMY.MAX_BREAK,breakRecoveryDelayTimer:CONFIG.ENEMY.INITIAL_RECOVERY_DELAY,breakStateTimer:CONFIG.ENEMY.INITIAL_BREAK_TIMER,isBroken:false,lastBreakSource:null,finisherAvailable:false,first};}
function spawnEnemy(){if(gameState.spawned>=CONFIG.ENEMY.TOTAL||gameState.enemies.filter(e=>e.active&&e.state!=="defeated").length>=CONFIG.ENEMY.MAX_ACTIVE)return;gameState.enemies.push(createEnemy());gameState.spawned++;}
function validEnemy(e){return Boolean(e&&e.active&&e.state!=="defeated");}
function setEnemyState(e,state,timer){e.state=state;e.stateTimer=Math.max(0,timer);e.vulnerable=state==="recovery";}
function beginTelegraph(e){e.actionSerial++;e.throwResolvedSerial=-1;setEnemyState(e,"telegraph",CONFIG.ENEMY.TELEGRAPH);}
function isEnemyInCounterWindow(e){return Boolean(validEnemy(e)&&e.state==="telegraph"&&e.throwResolvedSerial!==e.actionSerial&&e.stateTimer<=CONFIG.BREAK.COUNTER_WINDOW&&e.stateTimer>0);}
function createIncomingBall(e,meta={rallyCount:0,justBoost:false}){if(!validEnemy(e)||e.isBroken)return false;const d=direction(gameState.player.x-e.x,gameState.player.y-e.y);const speed=clamp(CONFIG.BALL.INCOMING_SPEED*(1+meta.rallyCount*CONFIG.BALL.RALLY_SPEED_GAIN),CONFIG.BALL.INCOMING_SPEED,CONFIG.BALL.MAX_SPEED);gameState.incomingBalls.push({id:nextId(),active:true,x:e.x-25,y:e.y,vx:d.x*speed,vy:d.y*speed,radius:CONFIG.BALL.RADIUS,rallyCount:clamp(meta.rallyCount,0,CONFIG.BALL.MAX_RALLY_COUNT),justBoost:Boolean(meta.justBoost),sourceEnemyId:e.id});return true;}
function updateEnemyBreakRecovery(e,dt){if(e.isBroken||e.state==="telegraph"||e.state==="defeated")return;e.breakRecoveryDelayTimer=Math.max(0,e.breakRecoveryDelayTimer-dt);if(e.breakRecoveryDelayTimer===0)e.breakValue=clamp(e.breakValue-CONFIG.BREAK.RECOVERY_PER_SECOND*dt,0,e.maxBreak);}
function retainBreakAfterFailure(e){e.breakValue=clamp(e.maxBreak*CONFIG.BREAK.FAILED_BREAK_RETAIN_RATIO,0,e.maxBreak);}
function expireBrokenState(e){if(!e.isBroken)return;e.isBroken=false;e.finisherAvailable=false;retainBreakAfterFailure(e);e.breakRecoveryDelayTimer=CONFIG.BREAK.RECOVERY_DELAY;setEnemyState(e,"recovery",CONFIG.ENEMY.RECOVERY);burst(e.x,e.y,CONFIG.COLORS.muted,false);textFx("STANCE RECOVERED",e.x,e.y-55,CONFIG.COLORS.white);}
function updateEnemies(dt){for(const e of gameState.enemies){if(!e.active)continue;e.flash=Math.max(0,e.flash-dt);e.knockback=Math.max(0,e.knockback-120*dt);if(e.state==="defeated"){e.stateTimer-=dt;if(e.stateTimer<=0)e.active=false;continue;}if(e.state==="entering"){e.x=Math.max(e.targetX,e.x-CONFIG.ENEMY.ENTER_SPEED*dt);if(e.x<=e.targetX)setEnemyState(e,"idle",random(CONFIG.ENEMY.IDLE_MIN,CONFIG.ENEMY.IDLE_MAX));continue;}if(e.state==="broken"){e.breakStateTimer=clamp(e.breakStateTimer-dt,0,CONFIG.BREAK.FIRST_BROKEN_DURATION);if(e.breakStateTimer<=0)expireBrokenState(e);continue;}updateEnemyBreakRecovery(e,dt);e.stateTimer-=dt;if(e.state==="idle"&&e.stateTimer<=0)beginTelegraph(e);else if(e.state==="telegraph"&&e.stateTimer<=0){if(e.throwResolvedSerial!==e.actionSerial){e.throwResolvedSerial=e.actionSerial;createIncomingBall(e);}setEnemyState(e,"recovery",CONFIG.ENEMY.RECOVERY);textFx("OPEN!",e.x,e.y-72,CONFIG.COLORS.cyan);}else if(e.state==="recovery"&&e.stateTimer<=0)setEnemyState(e,"idle",random(CONFIG.ENEMY.IDLE_MIN,CONFIG.ENEMY.IDLE_MAX));}
  gameState.spawnTimer-=dt;if(gameState.spawnTimer<=0){spawnEnemy();gameState.spawnTimer=CONFIG.ENEMY.SPAWN_INTERVAL;}
}
function calculateTargetScore(e){const dy=Math.abs(e.y-gameState.player.y),aligned=dy<=CONFIG.TARGET.ALIGNED_Y;return-dy*CONFIG.TARGET.VERTICAL_WEIGHT-distance(e,gameState.player)*CONFIG.TARGET.DISTANCE_WEIGHT+(aligned&&e.isBroken?CONFIG.TARGET.BROKEN_BONUS:0)+(aligned&&e.breakValue/e.maxBreak>=CONFIG.BREAK.NEAR_FULL_RATIO?CONFIG.TARGET.NEAR_BREAK_BONUS:0)+(aligned&&e.vulnerable?CONFIG.TARGET.VULNERABLE_BONUS:0);}
function updateTargetLock(dt){const candidates=gameState.enemies.filter(validEnemy);if(!candidates.length){gameState.targetEnemyId=null;return;}const best=candidates.reduce((a,b)=>calculateTargetScore(a)>=calculateTargetScore(b)?a:b);const current=candidates.find(e=>e.id===gameState.targetEnemyId);gameState.targetLockTimer=Math.max(0,gameState.targetLockTimer-dt);if(!current||(best.id!==current.id&&gameState.targetLockTimer===0&&calculateTargetScore(best)>calculateTargetScore(current)+CONFIG.TARGET.SWITCH_THRESHOLD)){gameState.targetEnemyId=best.id;gameState.targetLockTimer=CONFIG.TARGET.LOCK_MIN_TIME;}}
function updatePlayer(dt){const p=gameState.player;p.invincible=Math.max(0,p.invincible-dt);p.timer=Math.max(0,p.timer-dt);if(p.timer===0&&p.action!=="catching")p.action="normal";if(p.action!=="hurt")p.action=gameState.input.catchHeld&&p.timer===0?"catching":p.action;let dx=0,dy=0;if(gameState.input.keys.has("KeyA")||gameState.input.keys.has("ArrowLeft"))dx--;if(gameState.input.keys.has("KeyD")||gameState.input.keys.has("ArrowRight"))dx++;if(gameState.input.keys.has("KeyW")||gameState.input.keys.has("ArrowUp"))dy--;if(gameState.input.keys.has("KeyS")||gameState.input.keys.has("ArrowDown"))dy++;if(dx||dy){const d=direction(dx,dy);p.x+=d.x*CONFIG.PLAYER.SPEED*dt;p.y+=d.y*CONFIG.PLAYER.SPEED*dt;}else if(gameState.input.pointerActive){const d=direction(gameState.input.pointerX-p.x,gameState.input.pointerY-p.y),m=distance(p,{x:gameState.input.pointerX,y:gameState.input.pointerY});if(m>5){p.x+=d.x*Math.min(CONFIG.PLAYER.SPEED*dt,m);p.y+=d.y*Math.min(CONFIG.PLAYER.SPEED*dt,m);}}p.x=clamp(p.x,CONFIG.PLAYER.MIN_X,CONFIG.PLAYER.MAX_X);p.y=clamp(p.y,CONFIG.PLAYER.MIN_Y,CONFIG.PLAYER.MAX_Y);}
function isJustCatch(){return gameState.input.catchHeld&&gameState.elapsedTime-gameState.input.catchPressedAt<=CONFIG.CATCH.JUST_WINDOW;}
function catchBall(ball){const just=isJustCatch();ball.active=false;gameState.heldBall={rallyCount:clamp(ball.rallyCount,0,CONFIG.BALL.MAX_RALLY_COUNT),justCaught:just||ball.justBoost};gameState.player.action="catchRecovery";gameState.player.timer=just?CONFIG.CATCH.JUST_RECOVERY:CONFIG.CATCH.NORMAL_RECOVERY;gameState.score+=just?CONFIG.SCORE.JUST_CATCH:CONFIG.SCORE.CATCH;gameState.combo++;gameState.comboTimer=3;gameState.tutorial.caught=true;if(ball.rallyCount)gameState.score+=CONFIG.SCORE.RALLY*ball.rallyCount;if(just)gameState.hitStop=CONFIG.CATCH.JUST_SLOW;burst(gameState.player.x+35,gameState.player.y,just?CONFIG.COLORS.cyan:CONFIG.COLORS.white,just);textFx(just?"JUST CATCH!":"CAUGHT!",gameState.player.x,gameState.player.y-52,just?CONFIG.COLORS.cyan:CONFIG.COLORS.white);}
function canPerformFinishReturn(target){return Boolean(gameState.heldBall&&target&&validEnemy(target)&&target.isBroken&&target.finisherAvailable&&!['throwing','hurt'].includes(gameState.player.action));}
function makeReturnBall(target,speed,returnType,finisherEligible){const d=direction(target.x-gameState.player.x,target.y-gameState.player.y),rallyCount=clamp(gameState.heldBall.rallyCount,0,CONFIG.BALL.MAX_RALLY_COUNT);return{id:nextId(),active:true,x:gameState.player.x+CONFIG.THROW.OFFSET,y:gameState.player.y,vx:d.x*speed,vy:d.y*speed,radius:CONFIG.BALL.RADIUS,targetEnemyId:target.id,returnType,breakDamage:0,finisherEligible,rallyCount,breakAppliedEnemyIds:new Set(),resolved:false};}
function createFinishReturn(target){if(!canPerformFinishReturn(target))return false;const ball=makeReturnBall(target,CONFIG.BREAK.FINISH_SPEED,"normal",true);gameState.returnedBalls.push(ball);gameState.heldBall=null;gameState.player.action="throwing";gameState.player.timer=CONFIG.BREAK.FINISH_RECOVERY;gameState.hitStop=CONFIG.FX.FINISH_STOP;gameState.backgroundDim=CONFIG.FX.DIM_TIME;gameState.finishEffect={active:true,life:CONFIG.FX.FINISH_LINE_TIME,maxLife:CONFIG.FX.FINISH_LINE_TIME,from:{x:gameState.player.x,y:gameState.player.y},targetEnemyId:target.id};textFx("FINISH RETURN",CONFIG.WIDTH/2,105,CONFIG.COLORS.break);return true;}
function throwHeldBall(){if(!gameState.heldBall||["throwing","hurt","catchRecovery"].includes(gameState.player.action))return;const target=gameState.enemies.find(e=>e.id===gameState.targetEnemyId&&validEnemy(e));if(!target)return;if(canPerformFinishReturn(target)){createFinishReturn(target);return;}const just=gameState.heldBall.justCaught;const ball=makeReturnBall(target,just?CONFIG.THROW.JUST_SPEED:CONFIG.THROW.NORMAL_SPEED,just?"just":gameState.heldBall.rallyCount?"rally":"normal",false);gameState.returnedBalls.push(ball);gameState.heldBall=null;gameState.player.action="throwing";gameState.player.timer=just?CONFIG.THROW.RUSH_RECOVERY:CONFIG.THROW.RECOVERY;burst(gameState.player.x+35,gameState.player.y,just?CONFIG.COLORS.cyan:CONFIG.COLORS.orange,just);}
function damagePlayer(ball){if(!ball.active||gameState.player.invincible>0)return;ball.active=false;gameState.player.hp--;gameState.player.invincible=CONFIG.PLAYER.INVINCIBILITY;gameState.player.action="hurt";gameState.player.timer=CONFIG.PLAYER.HURT_TIME;gameState.heldBall=null;gameState.combo=0;gameState.screenShake=CONFIG.FX.BIG_SHAKE;textFx("HIT",gameState.player.x,gameState.player.y-45,CONFIG.COLORS.red);}
function updateIncomingBalls(dt){const center={x:gameState.player.x+CONFIG.CATCH.OFFSET,y:gameState.player.y};for(const ball of gameState.incomingBalls){if(!ball.active)continue;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;trail(ball,CONFIG.COLORS.orange);if(gameState.player.action==="catching"&&overlaps(ball,center,ball.radius,CONFIG.CATCH.RADIUS))catchBall(ball);else if(overlaps(ball,gameState.player,ball.radius,CONFIG.PLAYER.HITBOX))damagePlayer(ball);else if(outside(ball))ball.active=false;}}
function calculateBreakDamage(ball,e){let damage=ball.returnType==="just"?CONFIG.BREAK.JUST_DAMAGE:ball.returnType==="counter"?CONFIG.BREAK.COUNTER_DAMAGE:CONFIG.BREAK.NORMAL_DAMAGE;if(e.state==="recovery"&&ball.returnType==="normal")damage*=CONFIG.BREAK.RECOVERY_HIT_MULTIPLIER;damage+=Math.min(CONFIG.BREAK.MAX_RALLY_BONUS,clamp(ball.rallyCount,0,CONFIG.BALL.MAX_RALLY_COUNT)*CONFIG.BREAK.RALLY_BONUS_PER_COUNT);return damage;}
function triggerEnemyBreak(e){if(e.isBroken||e.state==="defeated")return;e.isBroken=true;e.finisherAvailable=true;e.breakValue=e.maxBreak;e.breakStateTimer=e.first?CONFIG.BREAK.FIRST_BROKEN_DURATION:CONFIG.BREAK.BROKEN_DURATION;e.throwResolvedSerial=e.actionSerial;setEnemyState(e,"broken",e.breakStateTimer);gameState.tutorial.firstBreak=true;gameState.score+=CONFIG.SCORE.BREAK;gameState.hitStop=Math.max(gameState.hitStop,CONFIG.FX.COUNTER_STOP);gameState.screenShake=CONFIG.FX.BIG_SHAKE;burst(e.x,e.y,CONFIG.COLORS.break,true);textFx("BREAK",e.x,e.y-75,CONFIG.COLORS.break);textFx("THROW!",e.x,e.y-105,CONFIG.COLORS.white);}
function defeatEnemy(e,ball,label){if(!validEnemy(e)||ball.resolved)return;ball.resolved=true;ball.active=false;e.isBroken=false;e.finisherAvailable=false;e.breakStateTimer=0;setEnemyState(e,"defeated",CONFIG.ENEMY.DEFEAT_TIME);e.knockback=CONFIG.ENEMY.KNOCKBACK;gameState.defeated++;gameState.score+=CONFIG.SCORE.KO;gameState.combo+=3;gameState.screenShake=CONFIG.FX.BIG_SHAKE;burst(e.x,e.y,CONFIG.COLORS.white,true);textFx(label,e.x,e.y-45,CONFIG.COLORS.break);}
function triggerJustBreak(e,ball){gameState.score+=CONFIG.SCORE.JUST_HIT;gameState.hitStop=CONFIG.FX.FINISH_STOP;gameState.backgroundDim=CONFIG.FX.DIM_TIME;gameState.finishEffect={active:true,life:CONFIG.FX.FINISH_LINE_TIME,maxLife:CONFIG.FX.FINISH_LINE_TIME,from:{x:ball.x,y:ball.y},targetEnemyId:e.id};defeatEnemy(e,ball,"JUST BREAK");}
function applyBreakDamage(e,ball){if(!validEnemy(e)||e.isBroken||ball.breakAppliedEnemyIds.has(e.id))return;ball.breakAppliedEnemyIds.add(e.id);ball.breakDamage=calculateBreakDamage(ball,e);e.breakValue=clamp(e.breakValue+ball.breakDamage,0,e.maxBreak);e.breakRecoveryDelayTimer=CONFIG.BREAK.RECOVERY_DELAY;e.lastBreakSource=ball.returnType;e.flash=.14;gameState.score+=ball.returnType==="just"?CONFIG.SCORE.JUST_HIT:CONFIG.SCORE.HIT;if(e.breakValue>=e.maxBreak){if(ball.returnType==="just")triggerJustBreak(e,ball);else triggerEnemyBreak(e);}else{ball.active=false;burst(e.x,e.y,CONFIG.COLORS.orange,false);textFx(`BREAK +${Math.round(ball.breakDamage)}`,e.x,e.y-55,CONFIG.COLORS.orange);}}
function handleCounterReturn(e,ball){if(!isEnemyInCounterWindow(e)||ball.resolved)return false;e.throwResolvedSerial=e.actionSerial;ball.returnType="counter";e.knockback=CONFIG.ENEMY.KNOCKBACK;gameState.score+=CONFIG.SCORE.COUNTER;gameState.hitStop=CONFIG.FX.COUNTER_STOP;gameState.screenShake=CONFIG.FX.BIG_SHAKE;textFx("COUNTER",e.x,e.y-82,CONFIG.COLORS.orange);applyBreakDamage(e,ball);if(!e.isBroken&&e.state!=="defeated")setEnemyState(e,"recovery",CONFIG.ENEMY.RECOVERY);return true;}
function resolveFinishReturnHit(e,ball){if(!ball.finisherEligible||ball.resolved||!e.isBroken||!e.finisherAvailable)return false;gameState.score+=CONFIG.SCORE.FINISH;gameState.hitStop=CONFIG.FX.FINISH_STOP;gameState.backgroundDim=CONFIG.FX.DIM_TIME;defeatEnemy(e,ball,"FINISH RETURN");return true;}
function rallyReturn(e,ball){if(e.type!=="batter"||e.isBroken||e.state!=="idle"||ball.returnType==="just"||ball.rallyCount>=CONFIG.BALL.MAX_RALLY_COUNT)return false;ball.active=false;const count=clamp(ball.rallyCount+1,0,CONFIG.BALL.MAX_RALLY_COUNT);setEnemyState(e,"recovery",CONFIG.BATTER.RETURN_DELAY);createIncomingBall(e,{rallyCount:count,justBoost:ball.returnType==="just"});textFx(`RALLY x${count}`,e.x,e.y-65,CONFIG.COLORS.white);return true;}
function updateReturnedBalls(dt){for(const ball of gameState.returnedBalls){if(!ball.active)continue;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;trail(ball,ball.finisherEligible?CONFIG.COLORS.break:ball.returnType==="just"?CONFIG.COLORS.cyan:CONFIG.COLORS.white);for(const e of gameState.enemies){if(!ball.active||!validEnemy(e)||!overlaps(ball,e))continue;if(resolveFinishReturnHit(e,ball))break;if(handleCounterReturn(e,ball))break;if(rallyReturn(e,ball))break;applyBreakDamage(e,ball);break;}if(ball.active&&outside(ball))ball.active=false;}}
function outside(b){const m=CONFIG.BALL.CLEANUP_MARGIN;return b.x<-m||b.x>CONFIG.WIDTH+m||b.y<-m||b.y>CONFIG.HEIGHT+m;}
function updateEffects(dt){gameState.screenShake=Math.max(0,gameState.screenShake-20*dt);gameState.screenFlash=Math.max(0,gameState.screenFlash-dt);gameState.backgroundDim=Math.max(0,gameState.backgroundDim-dt);if(gameState.finishEffect){gameState.finishEffect.life-=dt;if(gameState.finishEffect.life<=0)gameState.finishEffect=null;}gameState.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;});gameState.texts.forEach(t=>{t.life-=dt;t.y-=22*dt;});gameState.trails.forEach(t=>t.life-=dt);}
function cleanup(){gameState.enemies=gameState.enemies.filter(x=>x.active);gameState.incomingBalls=gameState.incomingBalls.filter(x=>x.active);gameState.returnedBalls=gameState.returnedBalls.filter(x=>x.active);gameState.particles=gameState.particles.filter(x=>x.life>0);gameState.texts=gameState.texts.filter(x=>x.life>0);gameState.trails=gameState.trails.filter(x=>x.life>0);}
function update(dt){if(gameState.phase!=="playing")return;gameState.frame++;if(gameState.hitStop>0){gameState.hitStop=Math.max(0,gameState.hitStop-dt);dt*=CONFIG.FX.HIT_STOP_SCALE;}gameState.elapsedTime+=dt;if(gameState.input.throwRequested){gameState.input.throwRequested=false;throwHeldBall();}updatePlayer(dt);updateEnemies(dt);updateTargetLock(dt);updateIncomingBalls(dt);updateReturnedBalls(dt);updateEffects(dt);cleanup();gameState.comboTimer=Math.max(0,gameState.comboTimer-dt);if(!gameState.comboTimer)gameState.combo=0;if(gameState.player.hp<=0)finish(false);else if(gameState.defeated>=CONFIG.ENEMY.TOTAL)finish(true);syncHud();}
function finish(clear){if(gameState.phase!=="playing")return;gameState.result=clear?"clear":"defeat";gameState.dom["result-kicker"].textContent=clear?"RETURN PROTOCOL COMPLETE":"DRILL TERMINATED";gameState.dom["result-title"].textContent=clear?"CLEAR":"GAME OVER";gameState.dom["final-score"].textContent=String(gameState.score).padStart(CONFIG.VIEW.SCORE_DIGITS,"0");setPhase("gameover");}
function syncHud(){const p=gameState.player;gameState.dom.score.textContent=String(gameState.score).padStart(CONFIG.VIEW.SCORE_DIGITS,"0");gameState.dom.combo.textContent=gameState.combo?`x${gameState.combo}`:"—";gameState.dom.hp.textContent=p?Array.from({length:CONFIG.PLAYER.HP},(_,i)=>i<p.hp?"●":"○").join(" "):"—";gameState.dom.held.textContent=gameState.heldBall?(gameState.heldBall.justCaught?"JUST READY":"BALL READY"):"EMPTY";gameState.dom.held.classList.toggle("ready",Boolean(gameState.heldBall));gameState.dom.progress.textContent=`${gameState.defeated} / ${CONFIG.ENEMY.TOTAL}`;}
function burst(x,y,color,strong){const n=strong?CONFIG.FX.STRONG_PARTICLES:CONFIG.FX.PARTICLES;for(let i=0;i<n;i++){const a=Math.random()*CONFIG.TAU,s=random(45,200);gameState.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:CONFIG.FX.LIFE,maxLife:CONFIG.FX.LIFE,size:random(2,6)});}}
function textFx(text,x,y,color){gameState.texts.push({text,x,y,color,life:CONFIG.FX.TEXT_LIFE,maxLife:CONFIG.FX.TEXT_LIFE});}
function trail(ball,color){gameState.trails.push({x:ball.x,y:ball.y,radius:ball.radius,color,life:CONFIG.FX.TRAIL_LIFE,maxLife:CONFIG.FX.TRAIL_LIFE,rallyCount:ball.rallyCount});}
function renderBackground(ctx){const g=ctx.createLinearGradient(0,0,0,CONFIG.HEIGHT);g.addColorStop(0,CONFIG.COLORS.sky);g.addColorStop(1,CONFIG.COLORS.sky2);ctx.fillStyle=g;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);ctx.fillStyle=CONFIG.COLORS.ground;ctx.fillRect(0,300,CONFIG.WIDTH,240);ctx.strokeStyle=CONFIG.COLORS.line;ctx.globalAlpha=.45;for(let y=CONFIG.VIEW.GROUND_Y;y>300;y-=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CONFIG.WIDTH,y);ctx.stroke();}for(let x=-960;x<1920;x+=CONFIG.VIEW.GRID){ctx.beginPath();ctx.moveTo(480,300);ctx.lineTo(x,540);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle=CONFIG.COLORS.orange;ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(CONFIG.PLAYER.MAX_X,300);ctx.lineTo(CONFIG.PLAYER.MAX_X,540);ctx.stroke();ctx.setLineDash([]);}
function renderEnemyBreakGauge(ctx,e){if(e.state==="defeated")return;const w=74,h=8,x=e.x-w/2,y=e.y-e.radius-31,ratio=clamp(e.breakValue/e.maxBreak,0,1);ctx.save();ctx.fillStyle="#02070bdd";ctx.fillRect(x-2,y-2,w+4,h+4);ctx.fillStyle=ratio>=1?CONFIG.COLORS.break:ratio>=CONFIG.BREAK.HIGH_RATIO?CONFIG.COLORS.orange:CONFIG.COLORS.muted;ctx.globalAlpha=ratio>=1?.65+Math.sin(gameState.elapsedTime*16)*.35:1;ctx.fillRect(x,y,w*ratio,h);ctx.strokeStyle=CONFIG.COLORS.white;ctx.globalAlpha=.8;ctx.strokeRect(x,y,w,h);ctx.fillStyle=CONFIG.COLORS.white;ctx.font="800 9px ui-monospace";ctx.textAlign="center";ctx.fillText("BREAK",e.x,y-4);ctx.restore();}
function renderBrokenMarker(ctx,e){if(!e.isBroken)return;const pulse=1+Math.sin(gameState.elapsedTime*12)*.08;ctx.save();ctx.translate(e.x,e.y);ctx.scale(pulse,pulse);ctx.strokeStyle=CONFIG.COLORS.break;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,e.radius+18,0,CONFIG.TAU);ctx.stroke();for(let i=0;i<6;i++){const a=i*CONFIG.TAU/6;ctx.beginPath();ctx.moveTo(Math.cos(a)*12,Math.sin(a)*12);ctx.lineTo(Math.cos(a+.2)*(e.radius+12),Math.sin(a+.2)*(e.radius+12));ctx.stroke();}ctx.fillStyle=CONFIG.COLORS.break;ctx.font="900 22px Impact";ctx.textAlign="center";ctx.fillText("▼",0,-52);ctx.font="900 12px ui-monospace";ctx.fillText(`${e.breakStateTimer.toFixed(1)}s`,0,52);ctx.restore();}
function renderEnemy(ctx,e){ctx.save();ctx.translate(e.x+e.knockback,e.y);if(e.state==="defeated"){ctx.rotate(.8);ctx.globalAlpha=clamp(e.stateTimer/CONFIG.ENEMY.DEFEAT_TIME,0,1);}if(e.isBroken)ctx.rotate(-.18);ctx.fillStyle="#02060a";ctx.beginPath();ctx.ellipse(0,e.radius+15,34,9,0,0,CONFIG.TAU);ctx.fill();ctx.fillStyle=e.flash?CONFIG.COLORS.white:"#aab8ba";ctx.beginPath();ctx.arc(0,0,e.radius,0,CONFIG.TAU);ctx.fill();ctx.fillStyle="#172832";ctx.fillRect(-e.radius,2,e.radius*2,19);ctx.fillStyle=e.isBroken?CONFIG.COLORS.break:e.vulnerable?CONFIG.COLORS.cyan:CONFIG.COLORS.red;ctx.fillRect(-15,8,30,5);ctx.fillStyle=CONFIG.COLORS.orange;ctx.beginPath();ctx.arc(e.isBroken?-38:-25,e.isBroken?-15:1,9,0,CONFIG.TAU);ctx.fill();ctx.restore();if(e.state==="telegraph"){ctx.strokeStyle=isEnemyInCounterWindow(e)?CONFIG.COLORS.orange:CONFIG.COLORS.red;ctx.lineWidth=isEnemyInCounterWindow(e)?7:3;ctx.beginPath();ctx.arc(e.x,e.y,e.radius+14,-Math.PI/2,-Math.PI/2+CONFIG.TAU*(1-e.stateTimer/CONFIG.ENEMY.TELEGRAPH));ctx.stroke();}renderEnemyBreakGauge(ctx,e);renderBrokenMarker(ctx,e);}
function drawBall(ctx,b,color){ctx.save();ctx.shadowColor=color;ctx.shadowBlur=14;ctx.fillStyle=color;ctx.beginPath();ctx.arc(b.x,b.y,b.radius,0,CONFIG.TAU);ctx.fill();ctx.restore();}
function renderPlayer(ctx){const p=gameState.player;ctx.save();ctx.globalAlpha=p.invincible>0&&Math.floor(gameState.elapsedTime*16)%2?.35:1;ctx.translate(p.x,p.y);ctx.fillStyle=CONFIG.COLORS.white;ctx.beginPath();ctx.arc(0,0,p.radius,0,CONFIG.TAU);ctx.fill();ctx.fillStyle="#172b37";ctx.fillRect(-18,1,36,20);ctx.fillStyle=CONFIG.COLORS.cyan;ctx.fillRect(-13,7,26,5);ctx.fillStyle=CONFIG.COLORS.orange;ctx.beginPath();ctx.arc(p.action==="catching"?34:24,-2,12,0,CONFIG.TAU);ctx.fill();ctx.restore();if(p.action==="catching"){const c={x:p.x+CONFIG.CATCH.OFFSET,y:p.y};ctx.strokeStyle=isJustCatch()?CONFIG.COLORS.cyan:CONFIG.COLORS.white;ctx.setLineDash([9,7]);ctx.beginPath();ctx.arc(c.x,c.y,CONFIG.CATCH.RADIUS,0,CONFIG.TAU);ctx.stroke();ctx.setLineDash([]);}}
function renderFinishReturnEffect(ctx){const fx=gameState.finishEffect;if(!fx)return;const e=gameState.enemies.find(x=>x.id===fx.targetEnemyId);if(!e)return;ctx.save();ctx.globalAlpha=clamp(fx.life/fx.maxLife,0,1);ctx.strokeStyle=CONFIG.COLORS.break;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(fx.from.x,fx.from.y);ctx.lineTo(e.x,e.y);ctx.stroke();ctx.strokeStyle=CONFIG.COLORS.white;ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,70*(1-fx.life/fx.maxLife)+25,0,CONFIG.TAU);ctx.stroke();ctx.restore();}
function renderTutorial(ctx){if(gameState.phase!=="playing")return;let message="";if(!gameState.tutorial.caught&&gameState.elapsedTime<6)message="HOLD CATCH";else if(gameState.heldBall)message=gameState.enemies.some(e=>e.isBroken)?"BREAK — THROW!":"MOVE TO THEIR HEIGHT • RETURN";if(message){ctx.save();ctx.font="900 24px Impact";ctx.textAlign="center";ctx.strokeStyle=CONFIG.COLORS.shadow;ctx.lineWidth=7;ctx.strokeText(message,480,92);ctx.fillStyle=CONFIG.COLORS.white;ctx.fillText(message,480,92);ctx.restore();}}
function render(){const ctx=gameState.ctx;ctx.clearRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);ctx.save();ctx.translate(random(-gameState.screenShake,gameState.screenShake),random(-gameState.screenShake,gameState.screenShake));renderBackground(ctx);if(gameState.backgroundDim>0){ctx.fillStyle=`rgba(1,5,10,${.58*gameState.backgroundDim/CONFIG.FX.DIM_TIME})`;ctx.fillRect(0,0,CONFIG.WIDTH,CONFIG.HEIGHT);}for(const t of gameState.trails){ctx.globalAlpha=t.life/t.maxLife*(.35+t.rallyCount*.08);ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(t.x,t.y,t.radius,0,CONFIG.TAU);ctx.fill();}ctx.globalAlpha=1;gameState.enemies.forEach(e=>renderEnemy(ctx,e));gameState.incomingBalls.forEach(b=>drawBall(ctx,b,CONFIG.COLORS.orange));gameState.returnedBalls.forEach(b=>drawBall(ctx,b,b.finisherEligible?CONFIG.COLORS.break:b.returnType==="just"?CONFIG.COLORS.cyan:CONFIG.COLORS.white));if(gameState.heldBall)drawBall(ctx,{x:gameState.player.x,y:gameState.player.y-35,radius:CONFIG.BALL.RADIUS},gameState.heldBall.justCaught?CONFIG.COLORS.cyan:CONFIG.COLORS.orange);renderPlayer(ctx);renderFinishReturnEffect(ctx);for(const p of gameState.particles){ctx.globalAlpha=p.life/p.maxLife;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.textAlign="center";for(const t of gameState.texts){ctx.globalAlpha=t.life/t.maxLife;ctx.font="900 22px Impact";ctx.strokeStyle=CONFIG.COLORS.shadow;ctx.lineWidth=5;ctx.strokeText(t.text,t.x,t.y);ctx.fillStyle=t.color;ctx.fillText(t.text,t.x,t.y);}ctx.globalAlpha=1;renderTutorial(ctx);ctx.restore();}
function gameLoop(timestamp){if(!gameState.lastTimestamp)gameState.lastTimestamp=timestamp;const dt=Math.min(CONFIG.MAX_DELTA,(timestamp-gameState.lastTimestamp)/1000);gameState.lastTimestamp=timestamp;update(dt);render();gameState.animationFrame=requestAnimationFrame(gameLoop);}
function initialize(){cacheDom();bindEvents();resetGame();setPhase("start");gameState.animationFrame=requestAnimationFrame(gameLoop);}
document.addEventListener("DOMContentLoaded",initialize,{once:true});
